export const mix1Cfg = [
    [
        ["pink_x", "pink_y"],
        ["yellow_x", "yellow_y"],
        ["pink_x", "pink_y"],
        ["yellow_x", "yellow_y"],
        ["pink_x", "pink_y"],
        ["yellow_x", "yellow_y"],
        ["pink_x", "pink_y"],
        ["yellow_x", "yellow_y"],
        ["pink_x", "pink_y"],
        ["yellow_x", "yellow_y"],
    ],
    [
        ["blue_x_1", "blue_y_1"],
        ["yellow_x_1", "yellow_y_1"],
        ["purple_x_1", "purple_y_1"],
        ["orange_x_1", "orange_y_1"],
        ["red_x_1", "red_y_1"],
        ["green_x_1", "green_y_1"],
    ],
    [
        ["blue_in_1", "blue_in_2"],
        ["yellow_in_1", "yellow_in_2"],
        ["purple_in_1", "purple_in_2"],
        ["orange_in_1", "orange_in_2"],
        ["green_in_1", "green_in_2"],
        ["red_in_1", "red_in_2"],
        ["cyan_in_1", "cyan_in_2"],
    ],
    [
        ["in_x", "in_y"],
        ["in_x", "in_y"],
        ["in_x", "in_y"],
        ["in_x", "in_y"],
        ["in_x", "in_y"],
        ["in_x", "in_y"],
        ["in_x", "in_y"],
    ],
];
