import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1039: SkinTheme = {
    name: "skin_1039",
    game_bg: { gradientStart: "#3a3c3d", gradientEnd: "#3d3e40", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#2e2f31", gradientEnd: "#5a5b5c", angle: 90, intensity: 0.5 },
    board_line: "#212122",
    board_bg: "#292a2b",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#3c2b84", gradientEnd: "#a786f6", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffcd00", gradientEnd: "#ffcd00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#c6c1ff",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#353e42", gradientEnd: "#596061", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#b0bcc2", gradientEnd: "#abb8be", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#8e98a0", gradientEnd: "#8e98a0", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#8e98a0", gradientEnd: "#8e98a0", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#f4c300", gradientEnd: "#f4c300", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#4eed1d", gradientEnd: "#1bd803", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#23160D", 255],
        pause: ["#581010", 255],
        light: ["#FF6B6B", 255],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#252525",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f1e0b9", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#56565a", gradientEnd: "#56565a", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#212223", gradientEnd: "#212223", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#FFF8E7", gradientEnd: "#FFF8E7", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#EFC20F", gradientEnd: "#EFC20F", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#EFC20F", gradientEnd: "#EFC20F", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#EFC20F", gradientEnd: "#EFC20F", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#604429", gradientEnd: "#604429", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF5A", initColor: "#11AEFF" },
    comboTips2: { inColor: "#FFFFFF5A", initColor: "#00FFC7" },
    comboTips3: { inColor: "#FFFFFF5A", initColor: "#FFFA16" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE0D", middle: "#EAB700", bottom: "#886000" },
            preClear: "#FFCE0D",
            encourageAni: {
                label: ["#FFDB4F", 255],
                outline: ["#746734", 255],
                light: ["#FFD010", 157],
                star: ["#FFED4A", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE0D", middle: "#EAB700", bottom: "#886000" },
            preClear: "#FFCE0D",
            encourageAni: {
                label: ["#FFDB4F", 255],
                outline: ["#746734", 255],
                light: ["#FFD010", 157],
                star: ["#FFED4A", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE0D", middle: "#EAB700", bottom: "#886000" },
            preClear: "#FFCE0D",
            encourageAni: {
                label: ["#FFDB4F", 255],
                outline: ["#746734", 255],
                light: ["#FFD010", 157],
                star: ["#FFED4A", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE0D", middle: "#EAB700", bottom: "#886000" },
            preClear: "#FFCE0D",
            encourageAni: {
                label: ["#FFDB4F", 255],
                outline: ["#746734", 255],
                light: ["#FFD010", 157],
                star: ["#FFED4A", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE0D", middle: "#EAB700", bottom: "#886000" },
            preClear: "#FFCE0D",
            encourageAni: {
                label: ["#FFDB4F", 255],
                outline: ["#746734", 255],
                light: ["#FFD010", 157],
                star: ["#FFED4A", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE0D", middle: "#EAB700", bottom: "#886000" },
            preClear: "#FFCE0D",
            encourageAni: {
                label: ["#FFDB4F", 255],
                outline: ["#746734", 255],
                light: ["#FFD010", 157],
                star: ["#FFED4A", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE0D", middle: "#EAB700", bottom: "#886000" },
            preClear: "#FFCE0D",
            encourageAni: {
                label: ["#FFDB4F", 255],
                outline: ["#746734", 255],
                light: ["#FFD010", 157],
                star: ["#FFED4A", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
    },
};
