import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1037: SkinTheme = {
    name: "skin_1037",
    game_bg: { gradientStart: "#c99232", gradientEnd: "#a77319", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#8e651f", gradientEnd: "#d49b37", angle: 90, intensity: 0.5 },
    board_line: "#3f2708",
    board_bg: "#533917",
    crown: { gradientStart: "#ffd200", gradientEnd: "#ffc000", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffc000", gradientEnd: "#ffc000", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#b84816", gradientEnd: "#c1752a", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffcd00", gradientEnd: "#ffcd00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#FFDB95",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#a4722c", gradientEnd: "#ba863d", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#ebcd9c", gradientEnd: "#e4c48d", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#684513", gradientEnd: "#684513", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#684513", gradientEnd: "#684513", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fff438", gradientEnd: "#fff149", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#5cd120", gradientEnd: "#51c41b", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#4A291B", 255],
        pause: ["#FF4117", 255],
        light: ["#FF3C05", 255],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f4e4bc", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#ce9634", gradientEnd: "#ce9634", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#92610a", gradientEnd: "#92610a", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#FFFBE7", gradientEnd: "#FFFBE7", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#EBC62A", gradientEnd: "#EBC62A", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#EBC62A", gradientEnd: "#EBC62A", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#EBC62A", gradientEnd: "#EBC62A", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#ebc62a", gradientEnd: "#ebc62a", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#7a4423", gradientEnd: "#7a4423", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF5A", initColor: "#0094FF" },
    comboTips2: { inColor: "#FFFFFF5A", initColor: "#37FFE3" },
    comboTips3: { inColor: "#FFFFFF5A", initColor: "#FFFB30" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#502d16",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#fbd949", gradientEnd: "#fada50", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fff2af", gradientEnd: "#fff4ba", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#e8a21a", gradientEnd: "#e6a21a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffe859", gradientEnd: "#ffe056", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#f8c527", gradientEnd: "#edbe2c", angle: 90, intensity: 0.5 },
            clear: { top: "#FCD422", middle: "#D5B638", bottom: "#8B7019" },
            preClear: "#FCD422",
            encourageAni: {
                label: ["#DBB30D", 255],
                outline: ["#58572B", 255],
                light: ["#FCDA22", 173],
                star: ["#FFFC5F", 255],
            },
            combo: {
                comboSp: ["#ff5d1d", 255],
                comboSpBg: ["#ffcc30", 255],
                comboCount: ["#a024ff", 255],
                comboCountBg: ["#ffcc30", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#502d16",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#fbd949", gradientEnd: "#fada50", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fff2af", gradientEnd: "#fff4ba", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#e8a21a", gradientEnd: "#e6a21a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffe859", gradientEnd: "#ffe056", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#f8c527", gradientEnd: "#edbe2c", angle: 90, intensity: 0.5 },
            clear: { top: "#FCD422", middle: "#D5B638", bottom: "#8B7019" },
            preClear: "#FCD422",
            encourageAni: {
                label: ["#DBB30D", 255],
                outline: ["#58572B", 255],
                light: ["#FCDA22", 173],
                star: ["#FFFC5F", 255],
            },
            combo: {
                comboSp: ["#ff5d1d", 255],
                comboSpBg: ["#ffcc30", 255],
                comboCount: ["#a024ff", 255],
                comboCountBg: ["#ffcc30", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#502d16",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#fbd949", gradientEnd: "#fada50", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fff2af", gradientEnd: "#fff4ba", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#e8a21a", gradientEnd: "#e6a21a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffe859", gradientEnd: "#ffe056", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#f8c527", gradientEnd: "#edbe2c", angle: 90, intensity: 0.5 },
            clear: { top: "#FCD422", middle: "#D5B638", bottom: "#8B7019" },
            preClear: "#FCD422",
            encourageAni: {
                label: ["#DBB30D", 255],
                outline: ["#58572B", 255],
                light: ["#FCDA22", 173],
                star: ["#FFFC5F", 255],
            },
            combo: {
                comboSp: ["#ff5d1d", 255],
                comboSpBg: ["#ffcc30", 255],
                comboCount: ["#a024ff", 255],
                comboCountBg: ["#ffcc30", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#502d16",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#fbd949", gradientEnd: "#fada50", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fff2af", gradientEnd: "#fff4ba", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#e8a21a", gradientEnd: "#e6a21a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffe859", gradientEnd: "#ffe056", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#f8c527", gradientEnd: "#edbe2c", angle: 90, intensity: 0.5 },
            clear: { top: "#FCD422", middle: "#D5B638", bottom: "#8B7019" },
            preClear: "#FCD422",
            encourageAni: {
                label: ["#DBB30D", 255],
                outline: ["#58572B", 255],
                light: ["#FCDA22", 173],
                star: ["#FFFC5F", 255],
            },
            combo: {
                comboSp: ["#ff5d1d", 255],
                comboSpBg: ["#ffcc30", 255],
                comboCount: ["#a024ff", 255],
                comboCountBg: ["#ffcc30", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#502d16",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#fbd949", gradientEnd: "#fada50", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fff2af", gradientEnd: "#fff4ba", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#e8a21a", gradientEnd: "#e6a21a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffe859", gradientEnd: "#ffe056", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#f8c527", gradientEnd: "#edbe2c", angle: 90, intensity: 0.5 },
            clear: { top: "#FCD422", middle: "#D5B638", bottom: "#8B7019" },
            preClear: "#FCD422",
            encourageAni: {
                label: ["#DBB30D", 255],
                outline: ["#58572B", 255],
                light: ["#FCDA22", 173],
                star: ["#FFFC5F", 255],
            },
            combo: {
                comboSp: ["#ff5d1d", 255],
                comboSpBg: ["#ffcc30", 255],
                comboCount: ["#a024ff", 255],
                comboCountBg: ["#ffcc30", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#502d16",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#fbd949", gradientEnd: "#fada50", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fff2af", gradientEnd: "#fff4ba", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#e8a21a", gradientEnd: "#e6a21a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffe859", gradientEnd: "#ffe056", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#f8c527", gradientEnd: "#edbe2c", angle: 90, intensity: 0.5 },
            clear: { top: "#FCD422", middle: "#D5B638", bottom: "#8B7019" },
            preClear: "#FCD422",
            encourageAni: {
                label: ["#DBB30D", 255],
                outline: ["#58572B", 255],
                light: ["#FCDA22", 173],
                star: ["#FFFC5F", 255],
            },
            combo: {
                comboSp: ["#ff5d1d", 255],
                comboSpBg: ["#ffcc30", 255],
                comboCount: ["#a024ff", 255],
                comboCountBg: ["#ffcc30", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#502d16",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#fbd949", gradientEnd: "#fada50", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fff2af", gradientEnd: "#fff4ba", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#e8a21a", gradientEnd: "#e6a21a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffe859", gradientEnd: "#ffe056", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#f8c527", gradientEnd: "#edbe2c", angle: 90, intensity: 0.5 },
            clear: { top: "#FCD422", middle: "#D5B638", bottom: "#8B7019" },
            preClear: "#FCD422",
            encourageAni: {
                label: ["#DBB30D", 255],
                outline: ["#58572B", 255],
                light: ["#FCDA22", 173],
                star: ["#FFFC5F", 255],
            },
            combo: {
                comboSp: ["#ff5d1d", 255],
                comboSpBg: ["#ffcc30", 255],
                comboCount: ["#a024ff", 255],
                comboCountBg: ["#ffcc30", 255],
            },
        },
    },
};
