import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1036: SkinTheme = {
    name: "skin_1036",
    game_bg: { gradientStart: "#9c84d4", gradientEnd: "#a289da", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#8a73c1", gradientEnd: "#8a73c1", angle: 90, intensity: 0.5 },
    board_line: "#937dc8",
    board_bg: "#c6b1f7",
    crown: { gradientStart: "#ffde00", gradientEnd: "#ffae11", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffb33c", gradientEnd: "#ffc63c", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#6c00c7", gradientEnd: "#ae45ff", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffba00", gradientEnd: "#ffb400", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#ee8dff",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#5339a0", gradientEnd: "#aa8bed", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#c6c0fa", gradientEnd: "#bdb6f5", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#b6acfe", gradientEnd: "#b6acfe", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#b6acfe", gradientEnd: "#b6acfe", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fab000", gradientEnd: "#f4ac00", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#37ee3c", gradientEnd: "#0acc25", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#110812", 255],
        pause: ["#E5B429", 255],
        light: ["#FFB946", 150],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f4e4bc", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#bea5eb", gradientEnd: "#bea5eb", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#7e57c2", gradientEnd: "#7e57c2", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#FFE7FF", gradientEnd: "#FFE7FF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#E24BE1", gradientEnd: "#E24BE1", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#E24BE1", gradientEnd: "#E24BE1", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#dd5cfb", gradientEnd: "#dd5cfb", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#be64fe", gradientEnd: "#be64fe", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#4f3b7f", gradientEnd: "#4f3b7f", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#B8D6FF", initColor: "#3CBDFF" },
    comboTips2: { inColor: "#96FFED96", initColor: "#5FFFE9" },
    comboTips3: { inColor: "#FFF45C96", initColor: "#FFE12E" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#471347",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d142d0", gradientEnd: "#ca3ac9", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f79af7", gradientEnd: "#f488f4", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#931392", gradientEnd: "#8e108e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e76be7", gradientEnd: "#e76be7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#ab28aa", gradientEnd: "#b32eb2", angle: 90, intensity: 0.5 },
            clear: { top: "#DB00E0", middle: "#E144F1", bottom: "#EFAAFFC8" },
            preClear: "#DB00E0",
            encourageAni: {
                label: ["#FF41FE", 255],
                outline: ["#401C40", 255],
                light: ["#FF75FE", 150],
                star: ["#FF94FE", 255],
            },
            combo: {
                comboSp: ["#f5f4ff", 255],
                comboSpBg: ["#ff44fe", 255],
                comboCount: ["#ffee2d", 255],
                comboCountBg: ["#ff44fe", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#471347",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d142d0", gradientEnd: "#ca3ac9", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f79af7", gradientEnd: "#f488f4", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#931392", gradientEnd: "#8e108e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e76be7", gradientEnd: "#e76be7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#ab28aa", gradientEnd: "#b32eb2", angle: 90, intensity: 0.5 },
            clear: { top: "#DB00E0", middle: "#E144F1", bottom: "#EFAAFFC8" },
            preClear: "#DB00E0",
            encourageAni: {
                label: ["#FF41FE", 255],
                outline: ["#401C40", 255],
                light: ["#FF75FE", 150],
                star: ["#FF94FE", 255],
            },
            combo: {
                comboSp: ["#f5f4ff", 255],
                comboSpBg: ["#ff44fe", 255],
                comboCount: ["#ffee2d", 255],
                comboCountBg: ["#ff44fe", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#471347",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d142d0", gradientEnd: "#ca3ac9", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f79af7", gradientEnd: "#f488f4", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#931392", gradientEnd: "#8e108e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e76be7", gradientEnd: "#e76be7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#ab28aa", gradientEnd: "#b32eb2", angle: 90, intensity: 0.5 },
            clear: { top: "#DB00E0", middle: "#E144F1", bottom: "#EFAAFFC8" },
            preClear: "#DB00E0",
            encourageAni: {
                label: ["#FF41FE", 255],
                outline: ["#401C40", 255],
                light: ["#FF75FE", 150],
                star: ["#FF94FE", 255],
            },
            combo: {
                comboSp: ["#f5f4ff", 255],
                comboSpBg: ["#ff44fe", 255],
                comboCount: ["#ffee2d", 255],
                comboCountBg: ["#ff44fe", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#471347",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d142d0", gradientEnd: "#ca3ac9", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f79af7", gradientEnd: "#f488f4", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#931392", gradientEnd: "#8e108e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e76be7", gradientEnd: "#e76be7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#ab28aa", gradientEnd: "#b32eb2", angle: 90, intensity: 0.5 },
            clear: { top: "#DB00E0", middle: "#E144F1", bottom: "#EFAAFFC8" },
            preClear: "#DB00E0",
            encourageAni: {
                label: ["#FF41FE", 255],
                outline: ["#401C40", 255],
                light: ["#FF75FE", 150],
                star: ["#FF94FE", 255],
            },
            combo: {
                comboSp: ["#f5f4ff", 255],
                comboSpBg: ["#ff44fe", 255],
                comboCount: ["#ffee2d", 255],
                comboCountBg: ["#ff44fe", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#471347",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d142d0", gradientEnd: "#ca3ac9", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f79af7", gradientEnd: "#f488f4", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#931392", gradientEnd: "#8e108e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e76be7", gradientEnd: "#e76be7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#ab28aa", gradientEnd: "#b32eb2", angle: 90, intensity: 0.5 },
            clear: { top: "#DB00E0", middle: "#E144F1", bottom: "#EFAAFFC8" },
            preClear: "#DB00E0",
            encourageAni: {
                label: ["#FF41FE", 255],
                outline: ["#401C40", 255],
                light: ["#FF75FE", 150],
                star: ["#FF94FE", 255],
            },
            combo: {
                comboSp: ["#f5f4ff", 255],
                comboSpBg: ["#ff44fe", 255],
                comboCount: ["#ffee2d", 255],
                comboCountBg: ["#ff44fe", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#471347",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d142d0", gradientEnd: "#ca3ac9", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f79af7", gradientEnd: "#f488f4", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#931392", gradientEnd: "#8e108e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e76be7", gradientEnd: "#e76be7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#ab28aa", gradientEnd: "#b32eb2", angle: 90, intensity: 0.5 },
            clear: { top: "#DB00E0", middle: "#E144F1", bottom: "#EFAAFFC8" },
            preClear: "#DB00E0",
            encourageAni: {
                label: ["#FF41FE", 255],
                outline: ["#401C40", 255],
                light: ["#FF75FE", 150],
                star: ["#FF94FE", 255],
            },
            combo: {
                comboSp: ["#f5f4ff", 255],
                comboSpBg: ["#ff44fe", 255],
                comboCount: ["#ffee2d", 255],
                comboCountBg: ["#ff44fe", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#471347",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d142d0", gradientEnd: "#ca3ac9", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f79af7", gradientEnd: "#f488f4", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#931392", gradientEnd: "#8e108e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e76be7", gradientEnd: "#e76be7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#ab28aa", gradientEnd: "#b32eb2", angle: 90, intensity: 0.5 },
            clear: { top: "#DB00E0", middle: "#E144F1", bottom: "#EFAAFFC8" },
            preClear: "#DB00E0",
            encourageAni: {
                label: ["#FF41FE", 255],
                outline: ["#401C40", 255],
                light: ["#FF75FE", 150],
                star: ["#FF94FE", 255],
            },
            combo: {
                comboSp: ["#f5f4ff", 255],
                comboSpBg: ["#ff44fe", 255],
                comboCount: ["#ffee2d", 255],
                comboCountBg: ["#ff44fe", 255],
            },
        },
    },
};
