import { SkinTheme } from "./types";

export const skin_Brush0: SkinTheme = {
    name: "skin_Brush0",
    game_bg: { gradientStart: "#3a3c3d", gradientEnd: "#3d3e40", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#2e2f31", gradientEnd: "#5a5b5c", angle: 90, intensity: 0.5 },
    board_line: "#212122",
    board_bg: "#292a2b",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#3c2b84", gradientEnd: "#a786f6", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffcd00", gradientEnd: "#ffcd00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#c6c1ff",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#353e42", gradientEnd: "#596061", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#b0bcc2", gradientEnd: "#abb8be", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#8e98a0", gradientEnd: "#8e98a0", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#8e98a0", gradientEnd: "#8e98a0", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#f4c300", gradientEnd: "#f4c300", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#4eed1d", gradientEnd: "#1bd803", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#23160D", 255],
        pause: ["#581010", 255],
        light: ["#FF6B6B", 255],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f4e4bc", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#ce9634", gradientEnd: "#ce9634", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#92610a", gradientEnd: "#92610a", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF5A", initColor: "#11AEFF" },
    comboTips2: { inColor: "#FFFFFF5A", initColor: "#00FFC7" },
    comboTips3: { inColor: "#FFFFFF5A", initColor: "#FFFA16" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#26CCFF", middle: "#057799", bottom: "#1C4484" },
            encourageAni: {
                label: ["#0AB6C1", 255],
                outline: ["#582953", 200],
                light: ["#B8FFFB", 150],
                star: ["#FF99F6", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            preClear: "#FFCE3F",
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE3F", middle: "#896800", bottom: "#634B00" },
            encourageAni: {
                label: ["#FFC318", 255],
                outline: ["#5B4D19", 200],
                light: ["#FFE791", 150],
                star: ["#FFEEAE", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#efc20f", gradientEnd: "#efc20f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#B547FF", middle: "#A033EF", bottom: "#5A0080" },
            encourageAni: {
                label: ["#851DFF", 255],
                outline: ["#302063", 200],
                light: ["#C4B1FF", 200],
                star: ["#B9A3FF", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#ee702a", gradientEnd: "#ee702a", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FFA235", middle: "#994F33", bottom: "#632905" },
            encourageAni: {
                label: ["#FF740C", 255],
                outline: ["#482B16", 200],
                light: ["#FFC194", 200],
                star: ["#FFBD8C", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#dc4735", gradientEnd: "#dc4735", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#E2333D", middle: "#842128", bottom: "#4A171B" },
            encourageAni: {
                label: ["#E80021", 255],
                outline: ["#301111", 255],
                light: ["#FFB2AE", 150],
                star: ["#FF8D8D", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#2cbf1a", gradientEnd: "#2cbf1a", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#1CB200", middle: "#0F7F0C", bottom: "#174316" },
            encourageAni: {
                label: ["#10902C", 255],
                outline: ["#123B26", 200],
                light: ["#28E033", 200],
                star: ["#B4FFD8", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#1cb2af", gradientEnd: "#1cb2af", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#26CCFF", middle: "#057799", bottom: "#1C4484" },
            encourageAni: {
                label: ["#0AB6C1", 255],
                outline: ["#582953", 200],
                light: ["#B8FFFB", 150],
                star: ["#FF99F6", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
        block8: {
            name: "方块颜色8",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb486b", gradientEnd: "#eb486b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffdb4f", gradientEnd: "#ffdb4f", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#be9800", gradientEnd: "#be9800", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffd11a", gradientEnd: "#ffd11a", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d5ab08", gradientEnd: "#d5ab08", angle: 90, intensity: 0.5 },
            clear: { top: "#FF5580", middle: "#99203F", bottom: "#550D20" },
            encourageAni: {
                label: ["#E8005A", 255],
                outline: ["#2E0A18", 200],
                light: ["#FFB2C8", 150],
                star: ["#FF99BA", 255],
            },
            combo: {
                comboSp: ["#ffffff", 255],
                comboSpBg: ["#7f7f7f", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#7f7f7f", 255],
            },
        },
    },
};
