import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// changColor6 配色6
export const skin_1058: SkinTheme = {
    name: "skin_1058",
    game_bg: { gradientStart: "#ce3938", gradientEnd: "#bf292f", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#742020", gradientEnd: "#dc3b40", angle: 90, intensity: 0.5 },
    board_line: "#1e264a",
    board_bg: "#242c54",
    crown: { gradientStart: "#ffde00", gradientEnd: "#ffae11", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffb33c", gradientEnd: "#ffc63c", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#d83939", gradientEnd: "#e55656", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffba00", gradientEnd: "#ffb400", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#fc999e",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#9f3447", gradientEnd: "#fa6d9a", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#fa97c4", gradientEnd: "#f28db8", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#f9a1ce", gradientEnd: "#f9a1ce", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#f9a1ce", gradientEnd: "#f9a1ce", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fad100", gradientEnd: "#f4cc00", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#37ee3c", gradientEnd: "#0acc25", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#7F0D0D", 255],
        pause: ["#DE0101", 255],
        light: ["#FC4848", 171],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f4e4bc", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#cb767a", gradientEnd: "#cb767a", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#ac353b", gradientEnd: "#ac353b", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#FFFAE7", gradientEnd: "#FFFAE7", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#EA4C54", gradientEnd: "#EA4C54", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#EA4C54", gradientEnd: "#EA4C54", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#f7535c", gradientEnd: "#f7535c", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#ea4c54", gradientEnd: "#ea4c54", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#5e2428", gradientEnd: "#5e2428", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF", initColor: "#54A3FF" },
    comboTips2: { inColor: "#FFFFFF", initColor: "#00FFF0" },
    comboTips3: { inColor: "#FFFFFF", initColor: "#FFE600" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#620707",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#ce3938", gradientEnd: "#bf292f", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ee7e7f", gradientEnd: "#f09394", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#821e25", gradientEnd: "#881e1e", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#de4a49", gradientEnd: "#cb3d44", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#b82c2b", gradientEnd: "#992529", angle: 90, intensity: 0.5 },
            clear: { top: "#E2333D", middle: "#842128", bottom: "#4A171B" },
            preClear: "#E2333D",
            encourageAni: {
                label: ["#E80021", 255],
                outline: ["#301111", 255],
                light: ["#FFB2AE", 150],
                star: ["#FF8D8D", 255],
            },
            combo: {
                comboSp: ["#D4F2FC", 255],
                comboSpBg: ["#3451D1", 255],
                comboCount: ["#FEE632", 255],
                comboCountBg: ["#3451D1", 255],
            },
        },
    },
};
