import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1001: SkinTheme = {
    name: "skin_1001",
    game_bg: { gradientStart: "#eea2ad", gradientEnd: "#efa6b2", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#ca7b8b", gradientEnd: "#df8e9d", angle: 90, intensity: 0.5 },
    board_line: "#73353d",
    board_bg: "#7f3e45",
    crown: { gradientStart: "#ffea03", gradientEnd: "#ffd200", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffe50a", gradientEnd: "#ffce0a", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#d7458c", gradientEnd: "#f991b9", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffba00", gradientEnd: "#ffaa00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#b3246a",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#ec5488", gradientEnd: "#ec95a4", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#ffbdd0", gradientEnd: "#ffbbcf", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#9a4150", gradientEnd: "#9a4150", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#9a4150", gradientEnd: "#9a4150", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fed846", gradientEnd: "#fdd72f", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#61dc48", gradientEnd: "#60c34b", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#000000", 180],
        pause: ["#EF0064", 255],
        light: ["#FF44B1", 180],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f4e4bc", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#d27685", gradientEnd: "#d27685", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#a1465e", gradientEnd: "#a1465e", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#FFEFE7", gradientEnd: "#FFEFE7", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#EB608B", gradientEnd: "#EB608B", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#EEA3AD", gradientEnd: "#EEA3AD", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#ff718a", gradientEnd: "#ff718a", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#ff718a", gradientEnd: "#ff718a", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#8b2f64", gradientEnd: "#8b2f64", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF", initColor: "#70BDFF" },
    comboTips2: { inColor: "#FFFFFF", initColor: "#5AFFF6" },
    comboTips3: { inColor: "#FFFFFF", initColor: "#FFEE52" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#55172a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb608b", gradientEnd: "#eb608b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fba6c2", gradientEnd: "#fba6c2", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b0395b", gradientEnd: "#b0395b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f381a4", gradientEnd: "#f381a4", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d04974", gradientEnd: "#d04974", angle: 90, intensity: 0.5 },
            clear: { top: "#FF88AD", middle: "#DA4D7C", bottom: "#A21953" },
            preClear: "#FF88AD",
            encourageAni: {
                label: ["#FF265E", 255],
                outline: ["#60051D", 255],
                light: ["#FFD8E7", 200],
                star: ["#FFE6F0", 255],
            },
            combo: {
                comboSp: ["#FFFFFF", 255],
                comboSpBg: ["#FF4684", 255],
                comboCount: ["#FFF22E", 255],
                comboCountBg: ["#FF4684", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#55172a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb608b", gradientEnd: "#eb608b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fba6c2", gradientEnd: "#fba6c2", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b0395b", gradientEnd: "#b0395b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f381a4", gradientEnd: "#f381a4", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d04974", gradientEnd: "#d04974", angle: 90, intensity: 0.5 },
            clear: { top: "#FF88AD", middle: "#DA4D7C", bottom: "#A21953" },
            preClear: "#FF88AD",
            encourageAni: {
                label: ["#FF265E", 255],
                outline: ["#60051D", 255],
                light: ["#FFD8E7", 200],
                star: ["#FFE6F0", 255],
            },
            combo: {
                comboSp: ["#FFFFFF", 255],
                comboSpBg: ["#FF4684", 255],
                comboCount: ["#FFF22E", 255],
                comboCountBg: ["#FF4684", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#55172a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb608b", gradientEnd: "#eb608b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fba6c2", gradientEnd: "#fba6c2", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b0395b", gradientEnd: "#b0395b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f381a4", gradientEnd: "#f381a4", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d04974", gradientEnd: "#d04974", angle: 90, intensity: 0.5 },
            clear: { top: "#FF88AD", middle: "#DA4D7C", bottom: "#A21953" },
            preClear: "#FF88AD",
            encourageAni: {
                label: ["#FF265E", 255],
                outline: ["#60051D", 255],
                light: ["#FFD8E7", 200],
                star: ["#FFE6F0", 255],
            },
            combo: {
                comboSp: ["#FFFFFF", 255],
                comboSpBg: ["#FF4684", 255],
                comboCount: ["#FFF22E", 255],
                comboCountBg: ["#FF4684", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#55172a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb608b", gradientEnd: "#eb608b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fba6c2", gradientEnd: "#fba6c2", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b0395b", gradientEnd: "#b0395b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f381a4", gradientEnd: "#f381a4", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d04974", gradientEnd: "#d04974", angle: 90, intensity: 0.5 },
            clear: { top: "#FF88AD", middle: "#DA4D7C", bottom: "#A21953" },
            preClear: "#FF88AD",
            encourageAni: {
                label: ["#FF265E", 255],
                outline: ["#60051D", 255],
                light: ["#FFD8E7", 200],
                star: ["#FFE6F0", 255],
            },
            combo: {
                comboSp: ["#FFFFFF", 255],
                comboSpBg: ["#FF4684", 255],
                comboCount: ["#FFF22E", 255],
                comboCountBg: ["#FF4684", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#55172a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb608b", gradientEnd: "#eb608b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fba6c2", gradientEnd: "#fba6c2", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b0395b", gradientEnd: "#b0395b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f381a4", gradientEnd: "#f381a4", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d04974", gradientEnd: "#d04974", angle: 90, intensity: 0.5 },
            clear: { top: "#FF88AD", middle: "#DA4D7C", bottom: "#A21953" },
            preClear: "#FF88AD",
            encourageAni: {
                label: ["#FF265E", 255],
                outline: ["#60051D", 255],
                light: ["#FFD8E7", 200],
                star: ["#FFE6F0", 255],
            },
            combo: {
                comboSp: ["#FFFFFF", 255],
                comboSpBg: ["#FF4684", 255],
                comboCount: ["#FFF22E", 255],
                comboCountBg: ["#FF4684", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#55172a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb608b", gradientEnd: "#eb608b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fba6c2", gradientEnd: "#fba6c2", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b0395b", gradientEnd: "#b0395b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f381a4", gradientEnd: "#f381a4", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d04974", gradientEnd: "#d04974", angle: 90, intensity: 0.5 },
            clear: { top: "#FF88AD", middle: "#DA4D7C", bottom: "#A21953" },
            preClear: "#FF88AD",
            encourageAni: {
                label: ["#FF265E", 255],
                outline: ["#60051D", 255],
                light: ["#FFD8E7", 200],
                star: ["#FFE6F0", 255],
            },
            combo: {
                comboSp: ["#FFFFFF", 255],
                comboSpBg: ["#FF4684", 255],
                comboCount: ["#FFF22E", 255],
                comboCountBg: ["#FF4684", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#55172a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#eb608b", gradientEnd: "#eb608b", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#fba6c2", gradientEnd: "#fba6c2", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b0395b", gradientEnd: "#b0395b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f381a4", gradientEnd: "#f381a4", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d04974", gradientEnd: "#d04974", angle: 90, intensity: 0.5 },
            clear: { top: "#FF88AD", middle: "#DA4D7C", bottom: "#A21953" },
            preClear: "#FF88AD",
            encourageAni: {
                label: ["#FF265E", 255],
                outline: ["#60051D", 255],
                light: ["#FFD8E7", 200],
                star: ["#FFE6F0", 255],
            },
            combo: {
                comboSp: ["#FFFFFF", 255],
                comboSpBg: ["#FF4684", 255],
                comboCount: ["#FFF22E", 255],
                comboCountBg: ["#FF4684", 255],
            },
        },
    },
};
