import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1016: SkinTheme = {
    name: "skin_1016",
    game_bg: { gradientStart: "#49c9bb", gradientEnd: "#3bbaad", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#34998f", gradientEnd: "#339e92", angle: 90, intensity: 0.5 },
    board_line: "#25534e",
    board_bg: "#2d6660",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#f2b309", gradientEnd: "#f9aa11", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#825ac6", gradientEnd: "#b077c6", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffba00", gradientEnd: "#ffb400", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#dca6fe",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#1ea597", gradientEnd: "#49c5b7", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#58feeb", gradientEnd: "#4efbe7", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#60ffdf", gradientEnd: "#60ffdf", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#60ffdf", gradientEnd: "#60ffdf", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fff724", gradientEnd: "#ffe400", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#43f93d", gradientEnd: "#2aee3a", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#0E301E", 255],
        pause: ["#3CB071", 255],
        light: ["#3CB071", 255],
        show: ["#E7FFF2", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#bbb5b0", gradientEnd: "#d8d2ce", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#e5dfda", gradientEnd: "#f7f1ec", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8c8681", gradientEnd: "#aba4a0", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#cec8c3", gradientEnd: "#e8e2dd", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#a29c97", gradientEnd: "#bdb7b2", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#48aea3", gradientEnd: "#48aea3", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#11897d", gradientEnd: "#11897d", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#E7FFF1", gradientEnd: "#E7FFF1", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#3EBDB0", gradientEnd: "#3EBDB0", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#3EBDB0", gradientEnd: "#3EBDB0", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#4CE5D5", gradientEnd: "#4CE5D5", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#4ce5d5", gradientEnd: "#4ce5d5", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#2a6271", gradientEnd: "#2a6271", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#6CA8ED", initColor: "#5CA0F1" },
    comboTips2: { inColor: "#A0FFE2", initColor: "#00FFB2" },
    comboTips3: { inColor: "#FFF386", initColor: "#F2E45F" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#38442a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#98d47f", gradientEnd: "#90cb75", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ccffb6", gradientEnd: "#cdffb6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#6ba152", gradientEnd: "#6ba452", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ade496", gradientEnd: "#aae193", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#82c068", gradientEnd: "#7eb763", angle: 90, intensity: 0.5 },
            clear: { top: "#A8E68D", middle: "#7EB268", bottom: "#2C7642" },
            preClear: "#A8E68D",
            encourageAni: {
                label: ["#96D17C", 255],
                outline: ["#374D2D", 255],
                light: ["#96D17C", 255],
                star: ["#C3F7AC", 255],
            },
            combo: {
                comboSp: ["#dafff6", 255],
                comboSpBg: ["#019cd6", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#019cd6", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#3d3c1b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#cfcc7c", gradientEnd: "#cbc97a", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f1f1b6", gradientEnd: "#f1f1b6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a1a15d", gradientEnd: "#a09e5b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e0dd91", gradientEnd: "#d9da95", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#bbbb6c", gradientEnd: "#b6b365", angle: 90, intensity: 0.5 },
            clear: { top: "#E0DD9A", middle: "#A7A565", bottom: "#6F6F45" },
            preClear: "#E0DD9A",
            encourageAni: {
                label: ["#CDCB7B", 255],
                outline: ["#5E5D39", 255],
                light: ["#CDCB7B", 255],
                star: ["#F2F0A2", 255],
            },
            combo: {
                comboSp: ["#dafff6", 255],
                comboSpBg: ["#019cd6", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#019cd6", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#38442a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#98d47f", gradientEnd: "#90cb75", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ccffb6", gradientEnd: "#cdffb6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#6ba152", gradientEnd: "#6ba452", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ade496", gradientEnd: "#aae193", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#82c068", gradientEnd: "#7eb763", angle: 90, intensity: 0.5 },
            clear: { top: "#A8E68D", middle: "#7EB268", bottom: "#2C7642" },
            preClear: "#A8E68D",
            encourageAni: {
                label: ["#96D17C", 255],
                outline: ["#374D2D", 255],
                light: ["#96D17C", 255],
                star: ["#C3F7AC", 255],
            },
            combo: {
                comboSp: ["#dafff6", 255],
                comboSpBg: ["#019cd6", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#019cd6", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#3d3c1b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#cfcc7c", gradientEnd: "#cbc97a", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f1f1b6", gradientEnd: "#f1f1b6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a1a15d", gradientEnd: "#a09e5b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e0dd91", gradientEnd: "#d9da95", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#bbbb6c", gradientEnd: "#b6b365", angle: 90, intensity: 0.5 },
            clear: { top: "#E0DD9A", middle: "#A7A565", bottom: "#6F6F45" },
            preClear: "#E0DD9A",
            encourageAni: {
                label: ["#CDCB7B", 255],
                outline: ["#5E5D39", 255],
                light: ["#CDCB7B", 255],
                star: ["#F2F0A2", 255],
            },
            combo: {
                comboSp: ["#dafff6", 255],
                comboSpBg: ["#019cd6", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#019cd6", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#38442a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#98d47f", gradientEnd: "#90cb75", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ccffb6", gradientEnd: "#cdffb6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#6ba152", gradientEnd: "#6ba452", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ade496", gradientEnd: "#aae193", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#82c068", gradientEnd: "#7eb763", angle: 90, intensity: 0.5 },
            clear: { top: "#A8E68D", middle: "#7EB268", bottom: "#2C7642" },
            preClear: "#A8E68D",
            encourageAni: {
                label: ["#96D17C", 255],
                outline: ["#374D2D", 255],
                light: ["#96D17C", 255],
                star: ["#C3F7AC", 255],
            },
            combo: {
                comboSp: ["#dafff6", 255],
                comboSpBg: ["#019cd6", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#019cd6", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#3d3c1b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#cfcc7c", gradientEnd: "#cbc97a", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f1f1b6", gradientEnd: "#f1f1b6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a1a15d", gradientEnd: "#a09e5b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e0dd91", gradientEnd: "#d9da95", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#bbbb6c", gradientEnd: "#b6b365", angle: 90, intensity: 0.5 },
            clear: { top: "#E0DD9A", middle: "#A7A565", bottom: "#6F6F45" },
            preClear: "#E0DD9A",
            encourageAni: {
                label: ["#CDCB7B", 255],
                outline: ["#5E5D39", 255],
                light: ["#CDCB7B", 255],
                star: ["#F2F0A2", 255],
            },
            combo: {
                comboSp: ["#dafff6", 255],
                comboSpBg: ["#019cd6", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#019cd6", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#38442a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#98d47f", gradientEnd: "#90cb75", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ccffb6", gradientEnd: "#cdffb6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#6ba152", gradientEnd: "#6ba452", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ade496", gradientEnd: "#aae193", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#82c068", gradientEnd: "#7eb763", angle: 90, intensity: 0.5 },
            clear: { top: "#A8E68D", middle: "#7EB268", bottom: "#2C7642" },
            preClear: "#A8E68D",
            encourageAni: {
                label: ["#96D17C", 255],
                outline: ["#374D2D", 255],
                light: ["#96D17C", 255],
                star: ["#C3F7AC", 255],
            },
            combo: {
                comboSp: ["#dafff6", 255],
                comboSpBg: ["#019cd6", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#019cd6", 255],
            },
        },
    },
};
