import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// 爆炸绿
export const skin_1042: SkinTheme = {
    name: "skin_1042",
    game_bg: { gradientStart: "#1ecb4f", gradientEnd: "#0fa63c", angle: 90, intensity: 0.6 },
    board_out_line: { gradientStart: "#7dff6b", gradientEnd: "#29e84e", angle: 90, intensity: 0.7 },
    board_line: "#2ecc52",
    board_bg: "#0d7a2a",
    crown: { gradientStart: "#ffee00", gradientEnd: "#ffbb00", angle: 90, intensity: 0.6 },
    crown_score: { gradientStart: "#fff200", gradientEnd: "#ffc700", angle: 90, intensity: 0.6 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#12b83e", gradientEnd: "#0d9630", angle: 90, intensity: 0.6 },
        bestscore_btn_bg: { gradientStart: "#ffee00", gradientEnd: "#ffc000", angle: 90, intensity: 0.6 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#ffee00",
        bestscore_parameter3: "#e8ffdf",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#0fbf42", gradientEnd: "#0da036", angle: 90, intensity: 0.6 },
        gameover_title: { gradientStart: "#d4ffb0", gradientEnd: "#baff8c", angle: 90, intensity: 0.6 },
        gameover_score_icon: { gradientStart: "#efffda", gradientEnd: "#efffda", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#efffda", gradientEnd: "#efffda", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#ffee00", gradientEnd: "#ffee00", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#7dff3a", gradientEnd: "#5de820", angle: 90, intensity: 0.6 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#004d10", 200],
        pause: ["#39ff14", 255],
        light: ["#b3ff70", 180],
        show: ["#ffffff", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#1a5c28",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#c8f5a0", gradientEnd: "#dfffbc", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f0ffdf", gradientEnd: "#faffed", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#6ec441", gradientEnd: "#82d44f", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#d6ffaa", gradientEnd: "#eaffcc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#8ad456", gradientEnd: "#a0e066", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#39ff14", gradientEnd: "#39ff14", angle: 90, intensity: 0.7 },
    travel_target_ribbon_down: { gradientStart: "#0aab2a", gradientEnd: "#0aab2a", angle: 90, intensity: 0.7 },
    comboTips1: { inColor: "#ffffff", initColor: "#39ff14" },
    comboTips2: { inColor: "#ffffff", initColor: "#00ffcc" },
    comboTips3: { inColor: "#ffffff", initColor: "#ffee00" },
    colors: {
        // 鲜绿
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#0d6b20",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#39ff14", gradientEnd: "#2de010", angle: 90, intensity: 0.6 },
            top: { gradientStart: "#b3ff80", gradientEnd: "#a0ff66", angle: 90, intensity: 0.6 },
            bottom: { gradientStart: "#1aaa0d", gradientEnd: "#179c0b", angle: 90, intensity: 0.6 },
            left: { gradientStart: "#6aff3a", gradientEnd: "#55ff25", angle: 90, intensity: 0.6 },
            right: { gradientStart: "#23cc0a", gradientEnd: "#1db508", angle: 90, intensity: 0.6 },
            clear: { top: "#39ff14", middle: "#7dff50", bottom: "#b3ff8096" },
            preClear: "#39ff14",
            encourageAni: {
                label: ["#39ff14", 255],
                outline: ["#004d00", 255],
                light: ["#b3ff80", 180],
                star: ["#e8ffcc", 255],
            },
            combo: {
                comboSp: ["#efffdf", 255],
                comboSpBg: ["#0aab2a", 255],
                comboCount: ["#ffee00", 255],
                comboCountBg: ["#0aab2a", 255],
            },
        },
        // 黄绿
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#4d6600",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#ccff00", gradientEnd: "#b8f000", angle: 90, intensity: 0.6 },
            top: { gradientStart: "#eeff80", gradientEnd: "#e4ff60", angle: 90, intensity: 0.6 },
            bottom: { gradientStart: "#7aaa00", gradientEnd: "#6e9900", angle: 90, intensity: 0.6 },
            left: { gradientStart: "#ddff33", gradientEnd: "#d4ff1a", angle: 90, intensity: 0.6 },
            right: { gradientStart: "#99cc00", gradientEnd: "#88bb00", angle: 90, intensity: 0.6 },
            clear: { top: "#ccff00", middle: "#deff55", bottom: "#eeff8096" },
            preClear: "#ccff00",
            encourageAni: {
                label: ["#ccff00", 255],
                outline: ["#334d00", 255],
                light: ["#eeff99", 180],
                star: ["#f5ffc0", 255],
            },
            combo: {
                comboSp: ["#f5ffcc", 255],
                comboSpBg: ["#7aaa00", 255],
                comboCount: ["#ff6600", 255],
                comboCountBg: ["#7aaa00", 255],
            },
        },
        // 青绿
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#006644",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#00ffaa", gradientEnd: "#00e89a", angle: 90, intensity: 0.6 },
            top: { gradientStart: "#80ffdd", gradientEnd: "#66ffcc", angle: 90, intensity: 0.6 },
            bottom: { gradientStart: "#00aa70", gradientEnd: "#009960", angle: 90, intensity: 0.6 },
            left: { gradientStart: "#33ffbb", gradientEnd: "#1affaa", angle: 90, intensity: 0.6 },
            right: { gradientStart: "#00cc88", gradientEnd: "#00bb77", angle: 90, intensity: 0.6 },
            clear: { top: "#00ffaa", middle: "#55ffc4", bottom: "#99ffe096" },
            preClear: "#00ffaa",
            encourageAni: {
                label: ["#00ffaa", 255],
                outline: ["#003322", 255],
                light: ["#99ffdd", 180],
                star: ["#ccfff0", 255],
            },
            combo: {
                comboSp: ["#e0fff5", 255],
                comboSpBg: ["#00aa70", 255],
                comboCount: ["#ffee00", 255],
                comboCountBg: ["#00aa70", 255],
            },
        },
        // 草绿
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#2d5c00",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#76e600", gradientEnd: "#68d000", angle: 90, intensity: 0.6 },
            top: { gradientStart: "#c0ff66", gradientEnd: "#b0ff4d", angle: 90, intensity: 0.6 },
            bottom: { gradientStart: "#4a9900", gradientEnd: "#428800", angle: 90, intensity: 0.6 },
            left: { gradientStart: "#99ee22", gradientEnd: "#88e011", angle: 90, intensity: 0.6 },
            right: { gradientStart: "#5ab800", gradientEnd: "#4fa600", angle: 90, intensity: 0.6 },
            clear: { top: "#76e600", middle: "#a4f033", bottom: "#c8ff8096" },
            preClear: "#76e600",
            encourageAni: {
                label: ["#76e600", 255],
                outline: ["#1a3300", 255],
                light: ["#bbff66", 180],
                star: ["#e4ffaa", 255],
            },
            combo: {
                comboSp: ["#eeffcc", 255],
                comboSpBg: ["#4a9900", 255],
                comboCount: ["#ff6600", 255],
                comboCountBg: ["#4a9900", 255],
            },
        },
        // 翠绿
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#005533",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#00e55c", gradientEnd: "#00cc50", angle: 90, intensity: 0.6 },
            top: { gradientStart: "#66ffaa", gradientEnd: "#4dff99", angle: 90, intensity: 0.6 },
            bottom: { gradientStart: "#009940", gradientEnd: "#008838", angle: 90, intensity: 0.6 },
            left: { gradientStart: "#33ff77", gradientEnd: "#1aff66", angle: 90, intensity: 0.6 },
            right: { gradientStart: "#00bb4c", gradientEnd: "#00aa44", angle: 90, intensity: 0.6 },
            clear: { top: "#00e55c", middle: "#44ff88", bottom: "#99ffc096" },
            preClear: "#00e55c",
            encourageAni: {
                label: ["#00e55c", 255],
                outline: ["#00331a", 255],
                light: ["#88ffbb", 180],
                star: ["#ccffe8", 255],
            },
            combo: {
                comboSp: ["#e0fff0", 255],
                comboSpBg: ["#009940", 255],
                comboCount: ["#ffee00", 255],
                comboCountBg: ["#009940", 255],
            },
        },
        // 苹果绿
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#336600",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#8fff00", gradientEnd: "#80ee00", angle: 90, intensity: 0.6 },
            top: { gradientStart: "#ccff66", gradientEnd: "#bbff4d", angle: 90, intensity: 0.6 },
            bottom: { gradientStart: "#55aa00", gradientEnd: "#4a9900", angle: 90, intensity: 0.6 },
            left: { gradientStart: "#aaff22", gradientEnd: "#99ff0d", angle: 90, intensity: 0.6 },
            right: { gradientStart: "#66cc00", gradientEnd: "#5abb00", angle: 90, intensity: 0.6 },
            clear: { top: "#8fff00", middle: "#b3ff44", bottom: "#d4ff8896" },
            preClear: "#8fff00",
            encourageAni: {
                label: ["#8fff00", 255],
                outline: ["#1a3300", 255],
                light: ["#ccff77", 180],
                star: ["#eeffbb", 255],
            },
            combo: {
                comboSp: ["#f0ffcc", 255],
                comboSpBg: ["#55aa00", 255],
                comboCount: ["#ff4444", 255],
                comboCountBg: ["#55aa00", 255],
            },
        },
        // 荧光绿（最亮，点睛）
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#004422",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0dff6e", gradientEnd: "#00ee60", angle: 90, intensity: 0.7 },
            top: { gradientStart: "#99ffcc", gradientEnd: "#77ffbb", angle: 90, intensity: 0.7 },
            bottom: { gradientStart: "#009944", gradientEnd: "#00883c", angle: 90, intensity: 0.7 },
            left: { gradientStart: "#44ff99", gradientEnd: "#22ff88", angle: 90, intensity: 0.7 },
            right: { gradientStart: "#00cc55", gradientEnd: "#00bb4d", angle: 90, intensity: 0.7 },
            clear: { top: "#0dff6e", middle: "#55ffaa", bottom: "#aaffdd96" },
            preClear: "#0dff6e",
            encourageAni: {
                label: ["#0dff6e", 255],
                outline: ["#002211", 255],
                light: ["#88ffcc", 180],
                star: ["#ccffee", 255],
            },
            combo: {
                comboSp: ["#e0fff5", 255],
                comboSpBg: ["#009944", 255],
                comboCount: ["#ffee00", 255],
                comboCountBg: ["#009944", 255],
            },
        },
    },
};
