import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// changColor6 配色5
export const skin_1057: SkinTheme = {
    name: "skin_1057",
    game_bg: { gradientStart: "#f0832e", gradientEnd: "#e1681a", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#643d23", gradientEnd: "#b67955", angle: 90, intensity: 0.5 },
    board_line: "#1e264a",
    board_bg: "#242c54",
    crown: { gradientStart: "#ffd200", gradientEnd: "#ffa800", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffc80b", gradientEnd: "#ffc80b", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#a161ff", gradientEnd: "#bb89ff", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffc500", gradientEnd: "#ffb500", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#8a42c6",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#066dcd", gradientEnd: "#58aaf0", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#a5e3f4", gradientEnd: "#95ddf1", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#125b96", gradientEnd: "#125b96", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#125b96", gradientEnd: "#125b96", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#ffbe23", gradientEnd: "#f4ac00", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#3de11e", gradientEnd: "#15d045", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#5180F9", 255],
        pause: ["#0E2665", 255],
        light: ["#163ADC", 255],
        show: ["#6D87FF", 180],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f4e4bc", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#6fb6f2", gradientEnd: "#6fb6f2", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#4693dd", gradientEnd: "#4693dd", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#E7FBFF", gradientEnd: "#E7FBFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#3E88FF", gradientEnd: "#3E88FF", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#1D6EF1", gradientEnd: "#1D6EF1", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#34A2FF", gradientEnd: "#34A2FF", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#34a2ff", gradientEnd: "#34a2ff", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#2f407b", gradientEnd: "#2f407b", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#1987E5", initColor: "#0089FF" },
    comboTips2: { inColor: "#20E6DB", initColor: "#00FFEF" },
    comboTips3: { inColor: "#E8D424", initColor: "#FFE600" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#531500",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f0832e", gradientEnd: "#e1681a", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffb87d", gradientEnd: "#febd7d", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a3490b", gradientEnd: "#9f4a0a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ff9142", gradientEnd: "#ed761d", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#c1621e", gradientEnd: "#bf5b11", angle: 90, intensity: 0.5 },
            clear: { top: "#FFA235", middle: "#994F33", bottom: "#632905" },
            preClear: "#FFA235",
            encourageAni: {
                label: ["#FF740C", 255],
                outline: ["#482B16", 200],
                light: ["#FFC194", 200],
                star: ["#FFBD8C", 255],
            },
            combo: {
                comboSp: ["#D4F2FC", 255],
                comboSpBg: ["#3451D1", 255],
                comboCount: ["#FEE632", 255],
                comboCountBg: ["#3451D1", 255],
            },
        },
    },
};
