import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// changColor6 配色4
export const skin_1056: SkinTheme = {
    name: "skin_1056",
    game_bg: { gradientStart: "#ebc13a", gradientEnd: "#e4a834", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#e3c29c", gradientEnd: "#dbbb9c", angle: 90, intensity: 0.5 },
    board_line: "#1e264a",
    board_bg: "#242c54",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffc000", gradientEnd: "#ffc000", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#933d2a", gradientEnd: "#ffaa72", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffe500", gradientEnd: "#ffd500", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#fab89d",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#78482d", gradientEnd: "#be8560", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#e5c7af", gradientEnd: "#dcbdab", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#e2aa88", gradientEnd: "#e2aa88", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#e2aa88", gradientEnd: "#e2aa88", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#ffc544", gradientEnd: "#ffd041", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#83d642", gradientEnd: "#7ed33d", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#2F210F", 255],
        pause: ["#FFBA33", 255],
        light: ["#FFA529", 150],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d4c783", gradientEnd: "#ebe29e", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f3f0b5", gradientEnd: "#fafbd3", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#917d47", gradientEnd: "#ad9755", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#e0d89d", gradientEnd: "#f2f0ba", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b3a56c", gradientEnd: "#d0c483", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#d49a74", gradientEnd: "#d49a74", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#895635", gradientEnd: "#895635", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#FFF0E7", gradientEnd: "#FFF0E7", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#E56A46", gradientEnd: "#E56A46", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#D46646", gradientEnd: "#D46646", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#DE6845", gradientEnd: "#DE6845", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#de6845", gradientEnd: "#de6845", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#5e3131", gradientEnd: "#5e3131", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#B6D5FF96", initColor: "#5CA7FF" },
    comboTips2: { inColor: "#E8FFFB96", initColor: "#37FFE3" },
    comboTips3: { inColor: "#FFF9A296", initColor: "#FFE230" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#562f00",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#ebc13a", gradientEnd: "#e4a834", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f8e370", gradientEnd: "#f8e177", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#b4771b", gradientEnd: "#b17216", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#fcd44c", gradientEnd: "#f1b435", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#c4981b", gradientEnd: "#ca8b1a", angle: 90, intensity: 0.5 },
            clear: { top: "#FFCE3F", middle: "#896800", bottom: "#634B00" },
            preClear: "#FFCE3F",
            encourageAni: {
                label: ["#FFC318", 255],
                outline: ["#5B4D19", 200],
                light: ["#FFE791", 150],
                star: ["#FFEEAE", 255],
            },
            combo: {
                comboSp: ["#D4F2FC", 255],
                comboSpBg: ["#3451D1", 255],
                comboCount: ["#FEE632", 255],
                comboCountBg: ["#3451D1", 255],
            },
        },
    },
};
