import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1034: SkinTheme = {
    name: "skin_1034",
    game_bg: { gradientStart: "#b09eda", gradientEnd: "#b9a2e0", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#947fb3", gradientEnd: "#9f8bc1", angle: 90, intensity: 0.5 },
    board_line: "#443a57",
    board_bg: "#52446b",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#f2b309", gradientEnd: "#f9aa11", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#855bdf", gradientEnd: "#b189f4", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffcd00", gradientEnd: "#ffcd00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#6b459d",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#947bc8", gradientEnd: "#b9a1e0", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#f0d4fc", gradientEnd: "#debcf8", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#f1d9ff", gradientEnd: "#f1d9ff", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#f1d9ff", gradientEnd: "#f1d9ff", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fab000", gradientEnd: "#f4ac00", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#4fe139", gradientEnd: "#57d747", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#000000", 180],
        pause: ["#AA37F1", 255],
        light: ["#DD8DFF", 180],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#beb3b3", gradientEnd: "#dbd0d0", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#e8dddd", gradientEnd: "#f9efef", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8b8080", gradientEnd: "#a99e9e", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#d1c6c6", gradientEnd: "#ebe0e0", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#a19696", gradientEnd: "#c0b5b5", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#9380c1", gradientEnd: "#9380c1", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#624993", gradientEnd: "#624993", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#F9E7FF", gradientEnd: "#F9E7FF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#B181FF", gradientEnd: "#B181FF", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#B181FF", gradientEnd: "#B181FF", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#B181FF", gradientEnd: "#B181FF", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#b181ff", gradientEnd: "#b181ff", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#42335b", gradientEnd: "#42335b", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF", initColor: "#1B96FF" },
    comboTips2: { inColor: "#FFFFFF", initColor: "#1BFFF2" },
    comboTips3: { inColor: "#FFFFFF", initColor: "#FFE81B" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#3e234b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#957ce7", gradientEnd: "#9577f6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#bdabf3", gradientEnd: "#bdabf3", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#715cb2", gradientEnd: "#6f59ae", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad99f1", gradientEnd: "#a68ef2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#806bc4", gradientEnd: "#7e67d4", angle: 90, intensity: 0.5 },
            clear: { top: "#B7A0FF", middle: "#9379E3", bottom: "#6435A4" },
            preClear: "#B7A0FF",
            encourageAni: {
                label: ["#8F6AFF", 255],
                outline: ["#302063", 200],
                light: ["#D4AFFF", 200],
                star: ["#DCC7FF", 255],
            },
            combo: {
                comboSp: ["#ffd9ed", 255],
                comboSpBg: ["#db45dd", 255],
                comboCount: ["#ffdede", 255],
                comboCountBg: ["#c843ff", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#3e234b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#957ce7", gradientEnd: "#9577f6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#bdabf3", gradientEnd: "#bdabf3", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#715cb2", gradientEnd: "#6f59ae", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad99f1", gradientEnd: "#a68ef2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#806bc4", gradientEnd: "#7e67d4", angle: 90, intensity: 0.5 },
            clear: { top: "#B7A0FF", middle: "#9379E3", bottom: "#6435A4" },
            preClear: "#B7A0FF",
            encourageAni: {
                label: ["#8F6AFF", 255],
                outline: ["#302063", 200],
                light: ["#D4AFFF", 200],
                star: ["#DCC7FF", 255],
            },
            combo: {
                comboSp: ["#ffd9ed", 255],
                comboSpBg: ["#db45dd", 255],
                comboCount: ["#ffdede", 255],
                comboCountBg: ["#c843ff", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#3e234b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#957ce7", gradientEnd: "#9577f6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#bdabf3", gradientEnd: "#bdabf3", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#715cb2", gradientEnd: "#6f59ae", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad99f1", gradientEnd: "#a68ef2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#806bc4", gradientEnd: "#7e67d4", angle: 90, intensity: 0.5 },
            clear: { top: "#B7A0FF", middle: "#9379E3", bottom: "#6435A4" },
            preClear: "#B7A0FF",
            encourageAni: {
                label: ["#8F6AFF", 255],
                outline: ["#302063", 200],
                light: ["#D4AFFF", 200],
                star: ["#DCC7FF", 255],
            },
            combo: {
                comboSp: ["#ffd9ed", 255],
                comboSpBg: ["#db45dd", 255],
                comboCount: ["#ffdede", 255],
                comboCountBg: ["#c843ff", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#3e234b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#957ce7", gradientEnd: "#9577f6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#bdabf3", gradientEnd: "#bdabf3", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#715cb2", gradientEnd: "#6f59ae", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad99f1", gradientEnd: "#a68ef2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#806bc4", gradientEnd: "#7e67d4", angle: 90, intensity: 0.5 },
            clear: { top: "#B7A0FF", middle: "#9379E3", bottom: "#6435A4" },
            preClear: "#B7A0FF",
            encourageAni: {
                label: ["#8F6AFF", 255],
                outline: ["#302063", 200],
                light: ["#D4AFFF", 200],
                star: ["#DCC7FF", 255],
            },
            combo: {
                comboSp: ["#ffd9ed", 255],
                comboSpBg: ["#db45dd", 255],
                comboCount: ["#ffdede", 255],
                comboCountBg: ["#c843ff", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#3e234b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#957ce7", gradientEnd: "#9577f6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#bdabf3", gradientEnd: "#bdabf3", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#715cb2", gradientEnd: "#6f59ae", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad99f1", gradientEnd: "#a68ef2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#806bc4", gradientEnd: "#7e67d4", angle: 90, intensity: 0.5 },
            clear: { top: "#B7A0FF", middle: "#9379E3", bottom: "#6435A4" },
            preClear: "#B7A0FF",
            encourageAni: {
                label: ["#8F6AFF", 255],
                outline: ["#302063", 200],
                light: ["#D4AFFF", 200],
                star: ["#DCC7FF", 255],
            },
            combo: {
                comboSp: ["#ffd9ed", 255],
                comboSpBg: ["#db45dd", 255],
                comboCount: ["#ffdede", 255],
                comboCountBg: ["#c843ff", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#3e234b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#957ce7", gradientEnd: "#9577f6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#bdabf3", gradientEnd: "#bdabf3", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#715cb2", gradientEnd: "#6f59ae", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad99f1", gradientEnd: "#a68ef2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#806bc4", gradientEnd: "#7e67d4", angle: 90, intensity: 0.5 },
            clear: { top: "#B7A0FF", middle: "#9379E3", bottom: "#6435A4" },
            preClear: "#B7A0FF",
            encourageAni: {
                label: ["#8F6AFF", 255],
                outline: ["#302063", 200],
                light: ["#D4AFFF", 200],
                star: ["#DCC7FF", 255],
            },
            combo: {
                comboSp: ["#ffd9ed", 255],
                comboSpBg: ["#db45dd", 255],
                comboCount: ["#ffdede", 255],
                comboCountBg: ["#c843ff", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#3e234b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#957ce7", gradientEnd: "#9577f6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#bdabf3", gradientEnd: "#bdabf3", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#715cb2", gradientEnd: "#6f59ae", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad99f1", gradientEnd: "#a68ef2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#806bc4", gradientEnd: "#7e67d4", angle: 90, intensity: 0.5 },
            clear: { top: "#B7A0FF", middle: "#9379E3", bottom: "#6435A4" },
            preClear: "#B7A0FF",
            encourageAni: {
                label: ["#8F6AFF", 255],
                outline: ["#302063", 200],
                light: ["#D4AFFF", 200],
                star: ["#DCC7FF", 255],
            },
            combo: {
                comboSp: ["#ffd9ed", 255],
                comboSpBg: ["#db45dd", 255],
                comboCount: ["#ffdede", 255],
                comboCountBg: ["#c843ff", 255],
            },
        },
    },
};
