import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1038: SkinTheme = {
    name: "skin_1038",
    game_bg: { gradientStart: "#62d7e8", gradientEnd: "#bff7fe", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#c5f8ff", gradientEnd: "#c5f8ff", angle: 90, intensity: 0.5 },
    board_line: "#6fdaec",
    board_bg: "#cbf8ff",
    crown: { gradientStart: "#ffd513", gradientEnd: "#ffc002", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffe34b", gradientEnd: "#ffcf4c", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#29989c", gradientEnd: "#41deaa", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffcd00", gradientEnd: "#ffcd00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#9af6f2",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#55c3d4", gradientEnd: "#80c5cf", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#cdf9ff", gradientEnd: "#d8f4f2", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#2292a5", gradientEnd: "#2292a5", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#2292a5", gradientEnd: "#2292a5", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#f8de04", gradientEnd: "#f1c212", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#6be54e", gradientEnd: "#71e153", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#FFD6D6", 255],
        pause: ["#FF5F5F", 255],
        light: ["#FF4300", 255],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f1e0b8", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec6a0", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#67d9ea", gradientEnd: "#67d9ea", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#0fabc5", gradientEnd: "#0fabc5", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#E7FFF1", gradientEnd: "#E7FFF1", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#CBF8FF", gradientEnd: "#CBF8FF", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#90CCFF", gradientEnd: "#90CCFF", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#53E8FF", gradientEnd: "#53E8FF", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#53e8ff", gradientEnd: "#53e8ff", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#236771", gradientEnd: "#236771", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF5A", initColor: "#7FC1FF" },
    comboTips2: { inColor: "#FFFFFF5A", initColor: "#00FFBD" },
    comboTips3: { inColor: "#FFFFFF5A", initColor: "#F9E880" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#99343e",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f79595", gradientEnd: "#e88483", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffbebe", gradientEnd: "#febfbe", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#c15352", gradientEnd: "#be5152", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#fdaaaa", gradientEnd: "#f19b9b", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d47373", gradientEnd: "#d47373", angle: 90, intensity: 0.5 },
            clear: { top: "#FF766D", middle: "#F08C8C", bottom: "#F7C6C65E" },
            preClear: "#FF766D",
            encourageAni: {
                label: ["#FEAAAA", 255],
                outline: ["#E64F4F", 255],
                light: ["#FF9494", 170],
                star: ["#FFACAC", 255],
            },
            combo: {
                comboSp: ["#eaecee", 255],
                comboSpBg: ["#00c0de", 255],
                comboCount: ["#feeb3f", 255],
                comboCountBg: ["#00c0de", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#138d9b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#57e3f4", gradientEnd: "#68ccdf", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#c1fafe", gradientEnd: "#c2fcfb", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#36a4b7", gradientEnd: "#39aabd", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#94f3ff", gradientEnd: "#94f3ff", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#5bc7d3", gradientEnd: "#2dc3d5", angle: 90, intensity: 0.5 },
            clear: { top: "#28C7FF", middle: "#5BEDF2", bottom: "#93DFE87D" },
            preClear: "#28C7FF",
            encourageAni: {
                label: ["#37A5B8", 255],
                outline: ["#40686E", 255],
                light: ["#069CD0", 255],
                star: ["#94F3FF", 255],
            },
            combo: {
                comboSp: ["#eaecee", 255],
                comboSpBg: ["#00c0de", 255],
                comboCount: ["#feeb3f", 255],
                comboCountBg: ["#00c0de", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#a85d0c",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#ffc63f", gradientEnd: "#f4ba20", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f5ee94", gradientEnd: "#fdf2a0", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#ce8915", gradientEnd: "#cb7e0a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffda69", gradientEnd: "#fbd663", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#e4a311", gradientEnd: "#d8a80c", angle: 90, intensity: 0.5 },
            clear: { top: "#F7B700", middle: "#F9DB72", bottom: "#FEE7CD5C" },
            preClear: "#F7B700",
            encourageAni: {
                label: ["#FFC31A", 255],
                outline: ["#B08E25", 156],
                light: ["#FFF443", 160],
                star: ["#FFDA67", 255],
            },
            combo: {
                comboSp: ["#eaecee", 255],
                comboSpBg: ["#00c0de", 255],
                comboCount: ["#feeb3f", 255],
                comboCountBg: ["#00c0de", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#99343e",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f79595", gradientEnd: "#e88483", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffbebe", gradientEnd: "#febfbe", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#c15352", gradientEnd: "#be5152", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#fdaaaa", gradientEnd: "#f19b9b", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d47373", gradientEnd: "#d47373", angle: 90, intensity: 0.5 },
            clear: { top: "#FF766D", middle: "#F08C8C", bottom: "#F7C6C65E" },
            preClear: "#FF766D",
            encourageAni: {
                label: ["#FEAAAA", 255],
                outline: ["#E64F4F", 255],
                light: ["#FF9494", 170],
                star: ["#FFACAC", 255],
            },
            combo: {
                comboSp: ["#eaecee", 255],
                comboSpBg: ["#00c0de", 255],
                comboCount: ["#feeb3f", 255],
                comboCountBg: ["#00c0de", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#138d9b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#57e3f4", gradientEnd: "#68ccdf", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#c1fafe", gradientEnd: "#c2fcfb", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#36a4b7", gradientEnd: "#39aabd", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#94f3ff", gradientEnd: "#94f3ff", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#5bc7d3", gradientEnd: "#2dc3d5", angle: 90, intensity: 0.5 },
            clear: { top: "#28C7FF", middle: "#5BEDF2", bottom: "#93DFE87D" },
            preClear: "#28C7FF",
            encourageAni: {
                label: ["#37A5B8", 255],
                outline: ["#40686E", 255],
                light: ["#069CD0", 255],
                star: ["#94F3FF", 255],
            },
            combo: {
                comboSp: ["#eaecee", 255],
                comboSpBg: ["#00c0de", 255],
                comboCount: ["#feeb3f", 255],
                comboCountBg: ["#00c0de", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#a85d0c",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#ffc63f", gradientEnd: "#f4ba20", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f5ee94", gradientEnd: "#fdf2a0", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#ce8915", gradientEnd: "#cb7e0a", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffda69", gradientEnd: "#fbd663", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#e4a311", gradientEnd: "#d8a80c", angle: 90, intensity: 0.5 },
            clear: { top: "#F7B700", middle: "#F9DB72", bottom: "#FEE7CD5C" },
            preClear: "#F7B700",
            encourageAni: {
                label: ["#FFC31A", 255],
                outline: ["#B08E25", 156],
                light: ["#FFF443", 160],
                star: ["#FFDA67", 255],
            },
            combo: {
                comboSp: ["#eaecee", 255],
                comboSpBg: ["#00c0de", 255],
                comboCount: ["#feeb3f", 255],
                comboCountBg: ["#00c0de", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#99343e",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f79595", gradientEnd: "#e88483", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffbebe", gradientEnd: "#febfbe", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#c15352", gradientEnd: "#be5152", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#fdaaaa", gradientEnd: "#f19b9b", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d47373", gradientEnd: "#d47373", angle: 90, intensity: 0.5 },
            clear: { top: "#FF766D", middle: "#F08C8C", bottom: "#F7C6C65E" },
            preClear: "#FF766D",
            encourageAni: {
                label: ["#FEAAAA", 255],
                outline: ["#E64F4F", 255],
                light: ["#FF9494", 170],
                star: ["#FFACAC", 255],
            },
            combo: {
                comboSp: ["#eaecee", 255],
                comboSpBg: ["#00c0de", 255],
                comboCount: ["#feeb3f", 255],
                comboCountBg: ["#00c0de", 255],
            },
        },
    },
};
