import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1021: SkinTheme = {
    name: "skin_1021",
    game_bg: { gradientStart: "#f7f9fd", gradientEnd: "#f7f9fd", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#e0e6ef", gradientEnd: "#e0e6ef", angle: 90, intensity: 0.5 },
    board_line: "#d4dbe7",
    board_bg: "#fdfdfc",
    crown: { gradientStart: "#ffea03", gradientEnd: "#ffd200", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffe50a", gradientEnd: "#ffce0a", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#2d67a4", gradientEnd: "#5b9ce3", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffd500", gradientEnd: "#ffca00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#83c0ff",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#b4c5e1", gradientEnd: "#dde2ea", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#779deb", gradientEnd: "#6d91db", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#7284a2", gradientEnd: "#7284a2", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#7284a2", gradientEnd: "#7284a2", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#2b91f7", gradientEnd: "#2b91f7", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fea001", gradientEnd: "#fea001", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#2e96fa", gradientEnd: "#298ef8", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#0080FF", 255],
        pause: ["#77BBFF", 255],
        light: ["#8B97FF", 255],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#2f2f2f",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#b6c2d7", gradientEnd: "#d1d7e1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#dbe2ee", gradientEnd: "#fafbfb", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#828992", gradientEnd: "#9fa6b4", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#c5cfe1", gradientEnd: "#dfe3e7", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#9aa4b5", gradientEnd: "#b7bec9", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#3584d5", gradientEnd: "#3584d5", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#2863a0", gradientEnd: "#2863a0", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#E7F4FF", gradientEnd: "#E7F4FF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#0581FF", gradientEnd: "#0581FF", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#0581FF", gradientEnd: "#0581FF", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#0581FF", gradientEnd: "#0581FF", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#208eff", gradientEnd: "#208eff", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#1d3d69", gradientEnd: "#1d3d69", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#79F7FF96", initColor: "#0080FF64" },
    comboTips2: { inColor: "#92FFF096", initColor: "#00FFF064" },
    comboTips3: { inColor: "#FFE67596", initColor: "#FFE60064" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0776e5", gradientEnd: "#0466cc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#64aeff", gradientEnd: "#78c2ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#0f468a", gradientEnd: "#0c4d9f", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#1c83ed", gradientEnd: "#0970d7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#025cbc", gradientEnd: "#0c5bae", angle: 90, intensity: 0.5 },
            clear: { top: "#3976ED", middle: "#4280E3A0", bottom: "#C3D8FF64" },
            preClear: "#3976ED",
            encourageAni: {
                label: ["#3C85CF", 255],
                outline: ["#77BBFF", 255],
                light: ["#2F9FFF", 255],
                star: ["#58ABFF", 255],
            },
            combo: {
                comboSp: ["#d5f4fd", 255],
                comboSpBg: ["#2f3fbb", 255],
                comboCount: ["#fedd0e", 255],
                comboCountBg: ["#2f3fbb", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0776e5", gradientEnd: "#0466cc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#64aeff", gradientEnd: "#78c2ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#0f468a", gradientEnd: "#0c4d9f", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#1c83ed", gradientEnd: "#0970d7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#025cbc", gradientEnd: "#0c5bae", angle: 90, intensity: 0.5 },
            clear: { top: "#3976ED", middle: "#4280E3A0", bottom: "#C3D8FF64" },
            preClear: "#3976ED",
            encourageAni: {
                label: ["#3C85CF", 255],
                outline: ["#77BBFF", 255],
                light: ["#2F9FFF", 255],
                star: ["#58ABFF", 255],
            },
            combo: {
                comboSp: ["#d5f4fd", 255],
                comboSpBg: ["#2f3fbb", 255],
                comboCount: ["#fedd0e", 255],
                comboCountBg: ["#2f3fbb", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0776e5", gradientEnd: "#0466cc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#64aeff", gradientEnd: "#78c2ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#0f468a", gradientEnd: "#0c4d9f", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#1c83ed", gradientEnd: "#0970d7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#025cbc", gradientEnd: "#0c5bae", angle: 90, intensity: 0.5 },
            clear: { top: "#3976ED", middle: "#4280E3A0", bottom: "#C3D8FF64" },
            preClear: "#3976ED",
            encourageAni: {
                label: ["#3C85CF", 255],
                outline: ["#77BBFF", 255],
                light: ["#2F9FFF", 255],
                star: ["#58ABFF", 255],
            },
            combo: {
                comboSp: ["#d5f4fd", 255],
                comboSpBg: ["#2f3fbb", 255],
                comboCount: ["#fedd0e", 255],
                comboCountBg: ["#2f3fbb", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0776e5", gradientEnd: "#0466cc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#64aeff", gradientEnd: "#78c2ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#0f468a", gradientEnd: "#0c4d9f", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#1c83ed", gradientEnd: "#0970d7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#025cbc", gradientEnd: "#0c5bae", angle: 90, intensity: 0.5 },
            clear: { top: "#3976ED", middle: "#4280E3A0", bottom: "#C3D8FF64" },
            preClear: "#3976ED",
            encourageAni: {
                label: ["#3C85CF", 255],
                outline: ["#77BBFF", 255],
                light: ["#2F9FFF", 255],
                star: ["#58ABFF", 255],
            },
            combo: {
                comboSp: ["#d5f4fd", 255],
                comboSpBg: ["#2f3fbb", 255],
                comboCount: ["#fedd0e", 255],
                comboCountBg: ["#2f3fbb", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0776e5", gradientEnd: "#0466cc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#64aeff", gradientEnd: "#78c2ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#0f468a", gradientEnd: "#0c4d9f", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#1c83ed", gradientEnd: "#0970d7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#025cbc", gradientEnd: "#0c5bae", angle: 90, intensity: 0.5 },
            clear: { top: "#3976ED", middle: "#4280E3A0", bottom: "#C3D8FF64" },
            preClear: "#3976ED",
            encourageAni: {
                label: ["#3C85CF", 255],
                outline: ["#77BBFF", 255],
                light: ["#2F9FFF", 255],
                star: ["#58ABFF", 255],
            },
            combo: {
                comboSp: ["#d5f4fd", 255],
                comboSpBg: ["#2f3fbb", 255],
                comboCount: ["#fedd0e", 255],
                comboCountBg: ["#2f3fbb", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0776e5", gradientEnd: "#0466cc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#64aeff", gradientEnd: "#78c2ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#0f468a", gradientEnd: "#0c4d9f", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#1c83ed", gradientEnd: "#0970d7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#025cbc", gradientEnd: "#0c5bae", angle: 90, intensity: 0.5 },
            clear: { top: "#3976ED", middle: "#4280E3A0", bottom: "#C3D8FF64" },
            preClear: "#3976ED",
            encourageAni: {
                label: ["#3C85CF", 255],
                outline: ["#77BBFF", 255],
                light: ["#2F9FFF", 255],
                star: ["#58ABFF", 255],
            },
            combo: {
                comboSp: ["#d5f4fd", 255],
                comboSpBg: ["#2f3fbb", 255],
                comboCount: ["#fedd0e", 255],
                comboCountBg: ["#2f3fbb", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#0776e5", gradientEnd: "#0466cc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#64aeff", gradientEnd: "#78c2ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#0f468a", gradientEnd: "#0c4d9f", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#1c83ed", gradientEnd: "#0970d7", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#025cbc", gradientEnd: "#0c5bae", angle: 90, intensity: 0.5 },
            clear: { top: "#3976ED", middle: "#4280E3A0", bottom: "#C3D8FF64" },
            preClear: "#3976ED",
            encourageAni: {
                label: ["#3C85CF", 255],
                outline: ["#77BBFF", 255],
                light: ["#2F9FFF", 255],
                star: ["#58ABFF", 255],
            },
            combo: {
                comboSp: ["#d5f4fd", 255],
                comboSpBg: ["#2f3fbb", 255],
                comboCount: ["#fedd0e", 255],
                comboCountBg: ["#2f3fbb", 255],
            },
        },
    },
};
