import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// changColor6 配色8
export const skin_1060: SkinTheme = {
    name: "skin_1060",
    game_bg: { gradientStart: "#5370e6", gradientEnd: "#3b53d0", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#304479", gradientEnd: "#304478", angle: 90, intensity: 0.5 },
    board_line: "#1e264a",
    board_bg: "#242c54",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#f2b309", gradientEnd: "#f9aa11", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#855bdf", gradientEnd: "#b189f4", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffcd00", gradientEnd: "#ffcd00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#6b459d",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#947bc8", gradientEnd: "#b9a1e0", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#f0d4fc", gradientEnd: "#debcf8", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#f1d9ff", gradientEnd: "#f1d9ff", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#f1d9ff", gradientEnd: "#f1d9ff", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fab000", gradientEnd: "#f4ac00", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#4fe139", gradientEnd: "#57d747", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#000000", 180],
        pause: ["#AA37F1", 255],
        light: ["#DD8DFF", 180],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#beb3b3", gradientEnd: "#dbd0d0", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#e8dddd", gradientEnd: "#f9efef", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8b8080", gradientEnd: "#a99e9e", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#d1c6c6", gradientEnd: "#ebe0e0", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#a19696", gradientEnd: "#c0b5b5", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#9380c1", gradientEnd: "#9380c1", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#624993", gradientEnd: "#624993", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#F9E7FF", gradientEnd: "#F9E7FF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#B181FF", gradientEnd: "#B181FF", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#B181FF", gradientEnd: "#B181FF", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#B181FF", gradientEnd: "#B181FF", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#b181ff", gradientEnd: "#b181ff", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#42335b", gradientEnd: "#42335b", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF", initColor: "#1B96FF" },
    comboTips2: { inColor: "#FFFFFF", initColor: "#1BFFF2" },
    comboTips3: { inColor: "#FFFFFF", initColor: "#FFE81B" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#222d6d",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#5370e6", gradientEnd: "#3b53d0", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#8db4ff", gradientEnd: "#a6c3fe", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#2b3d95", gradientEnd: "#31439b", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#5379f2", gradientEnd: "#5462f0", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#3856cc", gradientEnd: "#3550ba", angle: 90, intensity: 0.5 },
            clear: { top: "#008EFF", middle: "#2647DB", bottom: "#0E2A9F" },
            preClear: "#008EFF",
            encourageAni: {
                label: ["#0F4DFF", 255],
                outline: ["#0E1D48", 255],
                light: ["#92E3FF", 200],
                star: ["#BBE7FF", 255],
            },
            combo: {
                comboSp: ["#D4F2FC", 255],
                comboSpBg: ["#3451D1", 255],
                comboCount: ["#FEE632", 255],
                comboCountBg: ["#3451D1", 255],
            },
        },
    },
};
