import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// changColor6 配色2
export const skin_1054: SkinTheme = {
    name: "skin_1054",
    game_bg: { gradientStart: "#405aa0", gradientEnd: "#374f8f", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#304479", gradientEnd: "#304478", angle: 90, intensity: 0.5 },
    board_line: "#1e264a",
    board_bg: "#242c54",
    crown: { gradientStart: "#c57cfe", gradientEnd: "#e8b6ff", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#cbb2ff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#7636b7", gradientEnd: "#7757c8", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffba00", gradientEnd: "#ffb400", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#d17af1",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#4d4b9c", gradientEnd: "#7174bf", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#b5b8fc", gradientEnd: "#a0a3f4", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#8aa7f2", gradientEnd: "#8aa7f2", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#8aa7f2", gradientEnd: "#8aa7f2", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#f9d446", gradientEnd: "#fedd30", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#65d00f", gradientEnd: "#49cc0c", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#FF7500", 255],
        pause: ["#FFD250", 255],
        light: ["#FFEB2F", 180],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#41332e",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#caaf8c", gradientEnd: "#e1cba8", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#ecdebd", gradientEnd: "#f6efd8", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#907358", gradientEnd: "#a9896b", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#d8c4a4", gradientEnd: "#ebdec1", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#ab9276", gradientEnd: "#c6ae8d", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#9670ec", gradientEnd: "#9670ec", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#714bc6", gradientEnd: "#714bc6", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF", initColor: "#54A3FF" },
    comboTips2: { inColor: "#FFFFFF", initColor: "#3693FF" },
    comboTips3: { inColor: "#FFFFFF", initColor: "#01F6E7" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#06435a",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#51c1ed", gradientEnd: "#2ca8d6", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#9ce9fe", gradientEnd: "#a1f0fd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#1b6b9f", gradientEnd: "#1d77ab", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#66d7f9", gradientEnd: "#38bfe0", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#3899d5", gradientEnd: "#238fc4", angle: 90, intensity: 0.5 },
            clear: { top: "#26CCFF", middle: "#057799", bottom: "#1C4484" },
            preClear: "#26CCFF",
            encourageAni: {
                label: ["#0AB6C1", 255],
                outline: ["#582953", 200],
                light: ["#B8FFFB", 150],
                star: ["#FF99F6", 255],
            },
            combo: {
                comboSp: ["#D4F2FC", 255],
                comboSpBg: ["#3451D1", 255],
                comboCount: ["#FEE632", 255],
                comboCountBg: ["#3451D1", 255],
            },
        },
    },
};
