import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// 全蓝
export const skin_1040: SkinTheme = {
    name: "skin_1040",
    game_bg: { gradientStart: "#5457b0", gradientEnd: "#4541a6", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#3b3887", gradientEnd: "#3a3589", angle: 90, intensity: 0.5 },
    board_line: "#1f1a4d",
    board_bg: "#322d61",
    crown: { gradientStart: "#c57cfe", gradientEnd: "#e8b6ff", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#cbb2ff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#7636b7", gradientEnd: "#7757c8", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffba00", gradientEnd: "#ffb400", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#d17af1",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#4d4b9c", gradientEnd: "#7174bf", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#b5b8fc", gradientEnd: "#a0a3f4", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#8aa7f2", gradientEnd: "#8aa7f2", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#8aa7f2", gradientEnd: "#8aa7f2", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#f9d446", gradientEnd: "#fedd30", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#65d00f", gradientEnd: "#49cc0c", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#FF7500", 255],
        pause: ["#FFD250", 255],
        light: ["#FFEB2F", 180],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#41332e",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#caaf8c", gradientEnd: "#e1cba8", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#ecdebd", gradientEnd: "#f6efd8", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#907358", gradientEnd: "#a9896b", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#d8c4a4", gradientEnd: "#ebdec1", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#ab9276", gradientEnd: "#c6ae8d", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#9670ec", gradientEnd: "#9670ec", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#714bc6", gradientEnd: "#714bc6", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF", initColor: "#54A3FF" },
    comboTips2: { inColor: "#FFFFFF", initColor: "#3693FF" },
    comboTips3: { inColor: "#FFFFFF", initColor: "#01F6E7" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#0a1e70",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#687dd4", gradientEnd: "#5268be", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#a8baff", gradientEnd: "#bbc8ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#34499e", gradientEnd: "#394fa4", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#798ee5", gradientEnd: "#657ad1", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#5268be", gradientEnd: "#4459af", angle: 90, intensity: 0.5 },
            clear: { top: "#8295F1", middle: "#566DCBDC", bottom: "#5065BFA5" },
            preClear: "#8295F1",
            encourageAni: {
                label: ["#4C64D9", 255],
                outline: ["#2F47BA", 255],
                light: ["#687EE3", 255],
                star: ["#9FB0FF", 255],
            },
            combo: {
                comboSp: ["#f2fffe", 255],
                comboSpBg: ["#2792ff", 255],
                comboCount: ["#ffd800", 255],
                comboCountBg: ["#2792ff", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#72494e",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f4cbd0", gradientEnd: "#deb5ba", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffeef1", gradientEnd: "#ffeef1", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a87f84", gradientEnd: "#b68d92", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffdee2", gradientEnd: "#f0c7cc", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d6adb2", gradientEnd: "#c49ba0", angle: 90, intensity: 0.5 },
            clear: { top: "#F4CDD2", middle: "#C89AA0B4", bottom: "#E3B4BA5F" },
            preClear: "#F4CDD2",
            encourageAni: {
                label: ["#CB8992", 255],
                outline: ["#826165", 255],
                light: ["#DAACB0", 255],
                star: ["#FFD6DB", 255],
            },
            combo: {
                comboSp: ["#f2fffe", 255],
                comboSpBg: ["#2792ff", 255],
                comboCount: ["#ffd800", 255],
                comboCountBg: ["#2792ff", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#2b3266",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#cbd1ff", gradientEnd: "#bcc3f7", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#e7eaff", gradientEnd: "#eaecff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#868dc1", gradientEnd: "#868dc1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#d4d9ff", gradientEnd: "#c0c7fb", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#a2a9dd", gradientEnd: "#9da4d8", angle: 90, intensity: 0.5 },
            clear: { top: "#C7D0FF", middle: "#7F8ED4B4", bottom: "#8B9BE35F" },
            preClear: "#C7D0FF",
            encourageAni: {
                label: ["#9CA8EA", 255],
                outline: ["#5165CB", 255],
                light: ["#A4B0ED", 255],
                star: ["#C7D0FF", 255],
            },
            combo: {
                comboSp: ["#f2fffe", 255],
                comboSpBg: ["#2792ff", 255],
                comboCount: ["#ffd800", 255],
                comboCountBg: ["#2792ff", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#3f0e7b",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#ab7be8", gradientEnd: "#8f5fcc", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#d9b7ff", gradientEnd: "#dbbbff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#6939a6", gradientEnd: "#6b3ba8", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#bf8ffd", gradientEnd: "#8d5dca", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#9464d1", gradientEnd: "#7444b1", angle: 90, intensity: 0.5 },
            clear: { top: "#C191FB", middle: "#8E5FC6", bottom: "#C191FB69" },
            preClear: "#C191FB",
            encourageAni: {
                label: ["#955BDA", 255],
                outline: ["#7432C3", 255],
                light: ["#A975E8", 255],
                star: ["#C191FB", 255],
            },
            combo: {
                comboSp: ["#f2fffe", 255],
                comboSpBg: ["#2792ff", 255],
                comboCount: ["#ffd800", 255],
                comboCountBg: ["#2792ff", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#214168",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#57b4fa", gradientEnd: "#2d9df7", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#a9d9fc", gradientEnd: "#b4ddfc", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#1569b1", gradientEnd: "#1772bf", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#7bc4fb", gradientEnd: "#48adfa", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#2998f2", gradientEnd: "#1e88e2", angle: 90, intensity: 0.5 },
            clear: { top: "#68BEFC", middle: "#4997D4B4", bottom: "#3EA0E869" },
            preClear: "#68BEFC",
            encourageAni: {
                label: ["#49A3E5", 255],
                outline: ["#1371B5", 255],
                light: ["#1F74B0", 255],
                star: ["#C8E8FF", 255],
            },
            combo: {
                comboSp: ["#f2fffe", 255],
                comboSpBg: ["#2792ff", 255],
                comboCount: ["#ffd800", 255],
                comboCountBg: ["#2792ff", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#72494e",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f4cbd0", gradientEnd: "#deb5ba", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#ffeef1", gradientEnd: "#ffeef1", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a87f84", gradientEnd: "#b68d92", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ffdee2", gradientEnd: "#f0c7cc", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#d6adb2", gradientEnd: "#c49ba0", angle: 90, intensity: 0.5 },
            clear: { top: "#F4CDD2", middle: "#C89AA0B4", bottom: "#E3B4BA5F" },
            preClear: "#F4CDD2",
            encourageAni: {
                label: ["#CB8992", 255],
                outline: ["#826165", 255],
                light: ["#DAACB0", 255],
                star: ["#FFD6DB", 255],
            },
            combo: {
                comboSp: ["#f2fffe", 255],
                comboSpBg: ["#2792ff", 255],
                comboCount: ["#ffd800", 255],
                comboCountBg: ["#2792ff", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#0a1e70",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#687dd4", gradientEnd: "#5268be", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#a8baff", gradientEnd: "#bbc8ff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#34499e", gradientEnd: "#394fa4", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#798ee5", gradientEnd: "#657ad1", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#5268be", gradientEnd: "#4459af", angle: 90, intensity: 0.5 },
            clear: { top: "#8295F1", middle: "#566DCBDC", bottom: "#5065BFA5" },
            preClear: "#8295F1",
            encourageAni: {
                label: ["#4C64D9", 255],
                outline: ["#2F47BA", 255],
                light: ["#687EE3", 255],
                star: ["#9FB0FF", 255],
            },
            combo: {
                comboSp: ["#f2fffe", 255],
                comboSpBg: ["#2792ff", 255],
                comboCount: ["#ffd800", 255],
                comboCountBg: ["#2792ff", 255],
            },
        },
    },
};
