import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";
// changColor6 配色7
export const skin_1059: SkinTheme = {
    name: "skin_1059",
    game_bg: { gradientStart: "#9466d2", gradientEnd: "#794dc2", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#8a73c1", gradientEnd: "#8a73c1", angle: 90, intensity: 0.5 },
    board_line: "#1e264a",
    board_bg: "#242c54",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#f2b309", gradientEnd: "#f9aa11", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#825ac6", gradientEnd: "#b077c6", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffba00", gradientEnd: "#ffb400", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#dca6fe",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#1ea597", gradientEnd: "#49c5b7", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#58feeb", gradientEnd: "#4efbe7", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#60ffdf", gradientEnd: "#60ffdf", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#60ffdf", gradientEnd: "#60ffdf", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#fff724", gradientEnd: "#ffe400", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#43f93d", gradientEnd: "#2aee3a", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#0E301E", 255],
        pause: ["#3CB071", 255],
        light: ["#3CB071", 255],
        show: ["#E7FFF2", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#bbb5b0", gradientEnd: "#d8d2ce", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#e5dfda", gradientEnd: "#f7f1ec", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8c8681", gradientEnd: "#aba4a0", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#cec8c3", gradientEnd: "#e8e2dd", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#a29c97", gradientEnd: "#bdb7b2", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#48aea3", gradientEnd: "#48aea3", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#11897d", gradientEnd: "#11897d", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#E7FFF1", gradientEnd: "#E7FFF1", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#3EBDB0", gradientEnd: "#3EBDB0", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#3EBDB0", gradientEnd: "#3EBDB0", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#4CE5D5", gradientEnd: "#4CE5D5", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#4ce5d5", gradientEnd: "#4ce5d5", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#2a6271", gradientEnd: "#2a6271", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#6CA8ED", initColor: "#5CA0F1" },
    comboTips2: { inColor: "#A0FFE2", initColor: "#00FFB2" },
    comboTips3: { inColor: "#FFF386", initColor: "#F2E45F" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#440761",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#9466d2", gradientEnd: "#794dc2", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#d498ed", gradientEnd: "#daa7f0", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5b3087", gradientEnd: "#613185", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#ad79dc", gradientEnd: "#905ad5", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#78489d", gradientEnd: "#6c3ba1", angle: 90, intensity: 0.5 },
            clear: { top: "#B547FF", middle: "#A033EF", bottom: "#5A0080" },
            preClear: "#B547FF",
            encourageAni: {
                label: ["#851DFF", 255],
                outline: ["#302063", 200],
                light: ["#C4B1FF", 200],
                star: ["#B9A3FF", 255],
            },
            combo: {
                comboSp: ["#D4F2FC", 255],
                comboSpBg: ["#3451D1", 255],
                comboCount: ["#FEE632", 255],
                comboCountBg: ["#3451D1", 255],
            },
        },
    },
};
