import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1024: SkinTheme = {
    name: "skin_1024",
    game_bg: { gradientStart: "#bebebe", gradientEnd: "#969696", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#535353", gradientEnd: "#d3d3d3", angle: 90, intensity: 0.5 },
    board_line: "#3b3b3b",
    board_bg: "#434343",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffc21c", gradientEnd: "#ffc21c", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#5b8cc1", gradientEnd: "#c2dbf7", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffd500", gradientEnd: "#ffca00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#5178a3",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#646f77", gradientEnd: "#a1a8ac", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#cddfee", gradientEnd: "#bfcfe0", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#434b60", gradientEnd: "#434b60", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#434b60", gradientEnd: "#434b60", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#f9d417", gradientEnd: "#ecb715", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#ffd500", gradientEnd: "#ffca00", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#592223", 255],
        pause: ["#FF0000", 255],
        light: ["#FEE7E7", 145],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#43322c",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f4e4bc", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#929497", gradientEnd: "#929497", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#6e7072", gradientEnd: "#6e7072", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#E7F9FF", gradientEnd: "#E7F9FF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#87C7E7", gradientEnd: "#87C7E7", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#87C7E7", gradientEnd: "#87C7E7", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#8DD2F4", gradientEnd: "#8DD2F4", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#8dd2f4", gradientEnd: "#8dd2f4", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#42697d", gradientEnd: "#42697d", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#FFFFFF", initColor: "#84BAF9" },
    comboTips2: { inColor: "#FFFFFF", initColor: "#4EF7ED" },
    comboTips3: { inColor: "#FFFFFF", initColor: "#F6E54B" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d9e2eb", gradientEnd: "#d4dfe8", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f1f8ff", gradientEnd: "#f6faff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a4b1be", gradientEnd: "#a4b1be", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e4ecf4", gradientEnd: "#e7eef5", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#becbd7", gradientEnd: "#bcc9d5", angle: 90, intensity: 0.5 },
            clear: { top: "#D9E3EC", middle: "#A0A7AB", bottom: "#606B74" },
            preClear: "#D9E3EC",
            encourageAni: {
                label: ["#FFFFFF", 255],
                outline: ["#56595B", 255],
                light: ["#FFFFFF", 105],
                star: ["#E5E8EA", 255],
            },
            combo: {
                comboSp: ["#f2f0ff", 255],
                comboSpBg: ["#a1afc9", 255],
                comboCount: ["#cfff7a", 255],
                comboCountBg: ["#a1afc9", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#481f13",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f0acb2", gradientEnd: "#efa1a7", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f3cdd0", gradientEnd: "#f2c2c6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#c3737a", gradientEnd: "#c0767c", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f1b4ba", gradientEnd: "#f1b5bb", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#cf8b91", gradientEnd: "#cb848a", angle: 90, intensity: 0.5 },
            clear: { top: "#F5A7AD", middle: "#B77E83", bottom: "#825058" },
            preClear: "#F5A7AD",
            encourageAni: {
                label: ["#FC9AA2", 255],
                outline: ["#A7464D", 255],
                light: ["#FFFFFF", 103],
                star: ["#FFCCD0", 255],
            },
            combo: {
                comboSp: ["#ffd4cd", 255],
                comboSpBg: ["#ff8484", 255],
                comboCount: ["#ffca6d", 255],
                comboCountBg: ["#ff8484", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#324a56",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#86c8e8", gradientEnd: "#8bc5e3", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#acdcf7", gradientEnd: "#a6d9f5", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#689dba", gradientEnd: "#6297b3", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#9dd3f2", gradientEnd: "#9cd3f2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#75aac8", gradientEnd: "#75aac8", angle: 90, intensity: 0.5 },
            clear: { top: "#8AC7E7", middle: "#658DA1", bottom: "#405F78" },
            preClear: "#8AC7E7",
            encourageAni: {
                label: ["#6ECDFF", 255],
                outline: ["#3A6A84", 255],
                light: ["#FFFFFF", 104],
                star: ["#B7D5E5", 255],
            },
            combo: {
                comboSp: ["#e3fdff", 255],
                comboSpBg: ["#2a93ec", 255],
                comboCount: ["#2590a0", 255],
                comboCountBg: ["#2a93ec", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d9e2eb", gradientEnd: "#d4dfe8", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f1f8ff", gradientEnd: "#f6faff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a4b1be", gradientEnd: "#a4b1be", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e4ecf4", gradientEnd: "#e7eef5", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#becbd7", gradientEnd: "#bcc9d5", angle: 90, intensity: 0.5 },
            clear: { top: "#D9E3EC", middle: "#A0A7AB", bottom: "#606B74" },
            preClear: "#D9E3EC",
            encourageAni: {
                label: ["#FFFFFF", 255],
                outline: ["#56595B", 255],
                light: ["#FFFFFF", 105],
                star: ["#E5E8EA", 255],
            },
            combo: {
                comboSp: ["#f2f0ff", 255],
                comboSpBg: ["#a1afc9", 255],
                comboCount: ["#cfff7a", 255],
                comboCountBg: ["#a1afc9", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#481f13",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#f0acb2", gradientEnd: "#efa1a7", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f3cdd0", gradientEnd: "#f2c2c6", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#c3737a", gradientEnd: "#c0767c", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#f1b4ba", gradientEnd: "#f1b5bb", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#cf8b91", gradientEnd: "#cb848a", angle: 90, intensity: 0.5 },
            clear: { top: "#F5A7AD", middle: "#B77E83", bottom: "#825058" },
            preClear: "#F5A7AD",
            encourageAni: {
                label: ["#FC9AA2", 255],
                outline: ["#A7464D", 255],
                light: ["#FFFFFF", 103],
                star: ["#FFCCD0", 255],
            },
            combo: {
                comboSp: ["#ffd4cd", 255],
                comboSpBg: ["#ff8484", 255],
                comboCount: ["#ffca6d", 255],
                comboCountBg: ["#ff8484", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#324a56",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#86c8e8", gradientEnd: "#8bc5e3", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#acdcf7", gradientEnd: "#a6d9f5", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#689dba", gradientEnd: "#6297b3", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#9dd3f2", gradientEnd: "#9cd3f2", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#75aac8", gradientEnd: "#75aac8", angle: 90, intensity: 0.5 },
            clear: { top: "#8AC7E7", middle: "#658DA1", bottom: "#405F78" },
            preClear: "#8AC7E7",
            encourageAni: {
                label: ["#6ECDFF", 255],
                outline: ["#3A6A84", 255],
                light: ["#FFFFFF", 104],
                star: ["#B7D5E5", 255],
            },
            combo: {
                comboSp: ["#e3fdff", 255],
                comboSpBg: ["#2a93ec", 255],
                comboCount: ["#2590a0", 255],
                comboCountBg: ["#2a93ec", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#252525",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#d9e2eb", gradientEnd: "#d4dfe8", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#f1f8ff", gradientEnd: "#f6faff", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#a4b1be", gradientEnd: "#a4b1be", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#e4ecf4", gradientEnd: "#e7eef5", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#becbd7", gradientEnd: "#bcc9d5", angle: 90, intensity: 0.5 },
            clear: { top: "#D9E3EC", middle: "#A0A7AB", bottom: "#606B74" },
            preClear: "#D9E3EC",
            encourageAni: {
                label: ["#FFFFFF", 255],
                outline: ["#56595B", 255],
                light: ["#FFFFFF", 105],
                star: ["#E5E8EA", 255],
            },
            combo: {
                comboSp: ["#f2f0ff", 255],
                comboSpBg: ["#a1afc9", 255],
                comboCount: ["#cfff7a", 255],
                comboCountBg: ["#a1afc9", 255],
            },
        },
    },
};
