import { BlockSkinConfig, GradientConfig } from "../SkinsManager";
import { SkinTheme } from "./types";

export const skin_1035: SkinTheme = {
    name: "skin_1035",
    game_bg: { gradientStart: "#45a2d3", gradientEnd: "#5bbfd4", angle: 90, intensity: 0.5 },
    board_out_line: { gradientStart: "#237eaa", gradientEnd: "#7ed7f1", angle: 90, intensity: 0.5 },
    board_line: "#003e58",
    board_bg: "#034f6f",
    crown: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    crown_score: { gradientStart: "#ffd303", gradientEnd: "#ffae00", angle: 90, intensity: 0.5 },
    winEndPage: {
        bestscore_bg: { gradientStart: "#7647e2", gradientEnd: "#a081ef", angle: 90, intensity: 0.5 },
        bestscore_btn_bg: { gradientStart: "#ffcd00", gradientEnd: "#ffcd00", angle: 90, intensity: 0.5 },
        bestscore_btn_icon: "#ffffff",
        bestscore_score: "#ffffff",
        bestscore_parameter1: "#FBB001",
        bestscore_parameter3: "#cdb2ff",
    },
    loseEndPage: {
        gameover_bg: { gradientStart: "#2992af", gradientEnd: "#41afcf", angle: 90, intensity: 0.5 },
        gameover_title: { gradientStart: "#96f1fb", gradientEnd: "#8fedf7", angle: 90, intensity: 0.5 },
        gameover_score_icon: { gradientStart: "#5adbff", gradientEnd: "#5adbff", angle: 90, intensity: 0.5 },
        gameover_bestscore_icon: { gradientStart: "#5adbff", gradientEnd: "#5adbff", angle: 90, intensity: 0.5 },
        gameover_score: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
        gameover_bestscore: { gradientStart: "#f4c300", gradientEnd: "#f4c300", angle: 90, intensity: 0.5 },
        gameover_btn_bg: { gradientStart: "#4eed1d", gradientEnd: "#1bd803", angle: 90, intensity: 0.5 },
        gameover_btn_icon: "#ffffff",
    },
    newHighScore: {
        outline: ["#050D14", 255],
        pause: ["#FFB629", 255],
        light: ["#FFC216", 150],
        show: ["#FFFFFF", 255],
    },
    travel_gemstone_substrate: {
        name: "旅行宝石的衬底",
        frameOuterColor: "#001413",
        borderWidth: 0.02,
        bevelWidth: 0.13,
        center: { gradientStart: "#d1b186", gradientEnd: "#e8cda1", angle: 90, intensity: 0.5 },
        top: { gradientStart: "#f1e0b9", gradientEnd: "#faf1d5", angle: 90, intensity: 0.5 },
        bottom: { gradientStart: "#8e6a4a", gradientEnd: "#aa8059", angle: 90, intensity: 0.5 },
        left: { gradientStart: "#dec69f", gradientEnd: "#f0e0bc", angle: 90, intensity: 0.5 },
        right: { gradientStart: "#b19370", gradientEnd: "#cdaf86", angle: 90, intensity: 0.5 },
    },
    travel_target_ribbon_up: { gradientStart: "#56b9d3", gradientEnd: "#56b9d3", angle: 90, intensity: 0.5 },
    travel_target_ribbon_down: { gradientStart: "#0477a8", gradientEnd: "#0477a8", angle: 90, intensity: 0.5 },
    revive_countdown: {
        parameter1: { gradientStart: "#E7FFFC", gradientEnd: "#E7FFFC", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#59BDD4", gradientEnd: "#59BDD4", angle: 0, intensity: 0.5 },
        parameter3: { gradientStart: "#59BDD4", gradientEnd: "#59BDD4", angle: 0, intensity: 0.5 },
    },
    revive_btn: {
        parameter1: { gradientStart: "#FFFFFF", gradientEnd: "#FFFFFF", angle: 0, intensity: 0.5 },
        parameter2: { gradientStart: "#44CBEA", gradientEnd: "#44CBEA", angle: 0, intensity: 0.5 },
    },
    revive_progressbar: { gradientStart: "#44cbea", gradientEnd: "#44cbea", angle: 90, intensity: 0.5 },
    revive_progressbar_line: { gradientStart: "#ffffff", gradientEnd: "#ffffff", angle: 90, intensity: 0.5 },
    revive_progressbar_bg: { gradientStart: "#265374", gradientEnd: "#265374", angle: 90, intensity: 0.5 },
    comboTips1: { inColor: "#A8CEFF96", initColor: "#6BAFFF" },
    comboTips2: { inColor: "#A0FFEF96", initColor: "#78FCEA" },
    comboTips3: { inColor: "#FFF78896", initColor: "#FFE64D" },
    colors: {
        block1: {
            name: "方块颜色1",
            frameOuterColor: "#001413",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#96e7e4", gradientEnd: "#96e7e4", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#b8fffd", gradientEnd: "#b8fffd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5bb4b1", gradientEnd: "#5bb4b1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#a5f9f6", gradientEnd: "#a5f9f6", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#7dd1cf", gradientEnd: "#7dd1cf", angle: 90, intensity: 0.5 },
            clear: { top: "#AFFCF9", middle: "#61BECD96", bottom: "#018DA196" },
            preClear: "#AFFCF9",
            encourageAni: {
                label: ["#96E7E4", 255],
                outline: ["#1F4D4C", 255],
                light: ["#C9FFFD", 150],
                star: ["#D5FFFE", 255],
            },
            combo: {
                comboSp: ["#d0fff3", 255],
                comboSpBg: ["#0087dc", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#0087dc", 255],
            },
        },
        block2: {
            name: "方块颜色2",
            frameOuterColor: "#001413",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#96e7e4", gradientEnd: "#96e7e4", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#b8fffd", gradientEnd: "#b8fffd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5bb4b1", gradientEnd: "#5bb4b1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#a5f9f6", gradientEnd: "#a5f9f6", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#7dd1cf", gradientEnd: "#7dd1cf", angle: 90, intensity: 0.5 },
            clear: { top: "#AFFCF9", middle: "#61BECD96", bottom: "#018DA196" },
            preClear: "#AFFCF9",
            encourageAni: {
                label: ["#96E7E4", 255],
                outline: ["#1F4D4C", 255],
                light: ["#C9FFFD", 150],
                star: ["#D5FFFE", 255],
            },
            combo: {
                comboSp: ["#d0fff3", 255],
                comboSpBg: ["#0087dc", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#0087dc", 255],
            },
        },
        block3: {
            name: "方块颜色3",
            frameOuterColor: "#001413",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#96e7e4", gradientEnd: "#96e7e4", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#b8fffd", gradientEnd: "#b8fffd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5bb4b1", gradientEnd: "#5bb4b1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#a5f9f6", gradientEnd: "#a5f9f6", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#7dd1cf", gradientEnd: "#7dd1cf", angle: 90, intensity: 0.5 },
            clear: { top: "#AFFCF9", middle: "#61BECD96", bottom: "#018DA196" },
            preClear: "#AFFCF9",
            encourageAni: {
                label: ["#96E7E4", 255],
                outline: ["#1F4D4C", 255],
                light: ["#C9FFFD", 150],
                star: ["#D5FFFE", 255],
            },
            combo: {
                comboSp: ["#d0fff3", 255],
                comboSpBg: ["#0087dc", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#0087dc", 255],
            },
        },
        block4: {
            name: "方块颜色4",
            frameOuterColor: "#001413",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#96e7e4", gradientEnd: "#96e7e4", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#b8fffd", gradientEnd: "#b8fffd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5bb4b1", gradientEnd: "#5bb4b1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#a5f9f6", gradientEnd: "#a5f9f6", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#7dd1cf", gradientEnd: "#7dd1cf", angle: 90, intensity: 0.5 },
            clear: { top: "#AFFCF9", middle: "#61BECD96", bottom: "#018DA196" },
            preClear: "#AFFCF9",
            encourageAni: {
                label: ["#96E7E4", 255],
                outline: ["#1F4D4C", 255],
                light: ["#C9FFFD", 150],
                star: ["#D5FFFE", 255],
            },
            combo: {
                comboSp: ["#d0fff3", 255],
                comboSpBg: ["#0087dc", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#0087dc", 255],
            },
        },
        block5: {
            name: "方块颜色5",
            frameOuterColor: "#001413",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#96e7e4", gradientEnd: "#96e7e4", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#b8fffd", gradientEnd: "#b8fffd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5bb4b1", gradientEnd: "#5bb4b1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#a5f9f6", gradientEnd: "#a5f9f6", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#7dd1cf", gradientEnd: "#7dd1cf", angle: 90, intensity: 0.5 },
            clear: { top: "#AFFCF9", middle: "#61BECD96", bottom: "#018DA196" },
            preClear: "#AFFCF9",
            encourageAni: {
                label: ["#96E7E4", 255],
                outline: ["#1F4D4C", 255],
                light: ["#C9FFFD", 150],
                star: ["#D5FFFE", 255],
            },
            combo: {
                comboSp: ["#d0fff3", 255],
                comboSpBg: ["#0087dc", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#0087dc", 255],
            },
        },
        block6: {
            name: "方块颜色6",
            frameOuterColor: "#001413",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#96e7e4", gradientEnd: "#96e7e4", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#b8fffd", gradientEnd: "#b8fffd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5bb4b1", gradientEnd: "#5bb4b1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#a5f9f6", gradientEnd: "#a5f9f6", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#7dd1cf", gradientEnd: "#7dd1cf", angle: 90, intensity: 0.5 },
            clear: { top: "#AFFCF9", middle: "#61BECD96", bottom: "#018DA196" },
            preClear: "#AFFCF9",
            encourageAni: {
                label: ["#96E7E4", 255],
                outline: ["#1F4D4C", 255],
                light: ["#C9FFFD", 150],
                star: ["#D5FFFE", 255],
            },
            combo: {
                comboSp: ["#d0fff3", 255],
                comboSpBg: ["#0087dc", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#0087dc", 255],
            },
        },
        block7: {
            name: "方块颜色7",
            frameOuterColor: "#001413",
            borderWidth: 0.02,
            bevelWidth: 0.13,
            center: { gradientStart: "#96e7e4", gradientEnd: "#96e7e4", angle: 90, intensity: 0.5 },
            top: { gradientStart: "#b8fffd", gradientEnd: "#b8fffd", angle: 90, intensity: 0.5 },
            bottom: { gradientStart: "#5bb4b1", gradientEnd: "#5bb4b1", angle: 90, intensity: 0.5 },
            left: { gradientStart: "#a5f9f6", gradientEnd: "#a5f9f6", angle: 90, intensity: 0.5 },
            right: { gradientStart: "#7dd1cf", gradientEnd: "#7dd1cf", angle: 90, intensity: 0.5 },
            clear: { top: "#AFFCF9", middle: "#61BECD96", bottom: "#018DA196" },
            preClear: "#AFFCF9",
            encourageAni: {
                label: ["#96E7E4", 255],
                outline: ["#1F4D4C", 255],
                light: ["#C9FFFD", 150],
                star: ["#D5FFFE", 255],
            },
            combo: {
                comboSp: ["#d0fff3", 255],
                comboSpBg: ["#0087dc", 255],
                comboCount: ["#ffea00", 255],
                comboCountBg: ["#0087dc", 255],
            },
        },
    },
};
